using Microsoft.AspNetCore.Components;

namespace EmployeeManagement.Client.Blazor.Samples.Skill;

#region skill-blazor-usage
// Blazor component showing factory injection and usage
public partial class EmployeeManagementComponent : ComponentBase
{
    [Inject]
    private IEmployeeFactory EmployeeFactory { get; set; } = null!;

    private IEmployee? _employee;

    protected override async Task OnInitializedAsync()
    {
        // Create a new employee
        _employee = await EmployeeFactory.Create("John", "Doe");
    }

    private async Task LoadEmployee(Guid id)
    {
        // Fetch existing employee
        _employee = await EmployeeFactory.Fetch(id);
    }

    private async Task SaveEmployee()
    {
        if (_employee == null) return;

        // Save routes to Insert/Update/Delete based on IsNew/IsDeleted
        _employee = await EmployeeFactory.Save(_employee);
    }
}

// Placeholder interfaces for demonstration
// (Actual interfaces are generated by RemoteFactory)
public interface IEmployeeFactory
{
    Task<IEmployee> Create(string firstName, string lastName);
    Task<IEmployee?> Fetch(Guid id);
    Task<IEmployee> Save(IEmployee employee);
}

public interface IEmployee
{
    Guid Id { get; }
    string FirstName { get; set; }
    string LastName { get; set; }
    bool IsNew { get; }
    bool IsDeleted { get; set; }
}
#endregion
