// src/Generator/Renderer/ClassFactoryRenderer.cs
// Renders factories for classes and records with the [Factory] attribute.

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Neatoo.RemoteFactory.FactoryGenerator;
using Neatoo.RemoteFactory.Generator.Model;

namespace Neatoo.RemoteFactory.Generator.Renderer;

/// <summary>
/// Renders factory code for classes and records with the [Factory] attribute.
/// </summary>
internal static class ClassFactoryRenderer
{
    /// <summary>
    /// Renders the complete factory source code for a class/record.
    /// </summary>
    public static string Render(FactoryGenerationUnit unit)
    {
        var model = unit.ClassFactory!;
        var mode = unit.Mode;

        var sb = new StringBuilder();

        // Header
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Using statements
        foreach (var u in unit.Usings)
        {
            sb.AppendLine(u);
        }

        // Add hosting using if there are events
        if (model.Events.Count > 0 && model.IsPartial)
        {
            sb.AppendLine("using Microsoft.Extensions.Hosting;");
        }

        // Add usings required by the inline factory pipeline (avoid duplicates)
        if (!unit.Usings.Any(u => u.Contains("Microsoft.Extensions.Logging")))
        {
            sb.AppendLine("using Microsoft.Extensions.Logging;");
        }

        // Add using for DynamicDependency attribute (IL trimming support)
        if (!unit.Usings.Any(u => u.Contains("System.Diagnostics.CodeAnalysis")))
        {
            sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        }

        // Add using for TryAddTransient (auth type registrations)
        if (!unit.Usings.Any(u => u.Contains("Microsoft.Extensions.DependencyInjection.Extensions")))
        {
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        }

        sb.AppendLine();
        sb.AppendLine("/*");
        sb.AppendLine("    READONLY - DO NOT EDIT!!!!");
        sb.AppendLine("    Generated by Neatoo.RemoteFactory");
        sb.AppendLine("*/");

        sb.AppendLine($"namespace {unit.Namespace}");
        sb.AppendLine("{");

        // Event partial class (if there are events and the class is partial)
        if (model.Events.Count > 0 && model.IsPartial)
        {
            RenderEventPartialClass(sb, model);
        }

        // Factory interface
        RenderFactoryInterface(sb, model);

        // Factory class
        RenderFactoryClass(sb, model, mode);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void RenderEventPartialClass(StringBuilder sb, ClassFactoryModel model)
    {
        sb.AppendLine($"    // Event delegates for {model.ImplementationTypeName}");
        sb.AppendLine($"    public partial class {model.ImplementationTypeName}");
        sb.AppendLine("    {");

        foreach (var evt in model.Events)
        {
            var paramDecl = string.Join(", ", evt.Parameters
                .Where(p => !p.IsCancellationToken)
                .Select(p => $"{p.Type} {p.Name}"));

            sb.AppendLine($"        public delegate Task {evt.DelegateName}({paramDecl});");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void RenderFactoryInterface(StringBuilder sb, ClassFactoryModel model)
    {
        var interfaceVisibility = model.AllMethodsInternal ? "internal" : "public";
        sb.AppendLine($"    {interfaceVisibility} interface I{model.ImplementationTypeName}Factory");
        sb.AppendLine("    {");

        bool firstMethod = true;
        foreach (var method in model.Methods)
        {
            // Internal methods on a public interface need the 'internal' modifier.
            // On an all-internal interface, no modifier is needed (the interface itself is internal).
            bool needsInternalPrefix = !model.AllMethodsInternal && method.IsInternal;

            var interfaceMethod = RenderInterfaceMethodSignature(method, needsInternalPrefix);
            if (!string.IsNullOrEmpty(interfaceMethod))
            {
                // [DynamicDependency] on the first interface method preserves the factory class
                // during IL trimming. The interface is kept (client code injects it), so this
                // ensures the concrete factory — discovered via reflection — survives trimming.
                if (firstMethod)
                {
                    sb.AppendLine($"        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof({model.ImplementationTypeName}Factory))]");
                    firstMethod = false;
                }
                sb.AppendLine($"        {interfaceMethod}");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string RenderInterfaceMethodSignature(FactoryMethodModel method, bool needsInternalPrefix)
    {
        // Skip write methods as they're only used internally by Save
        if (method is WriteMethodModel)
        {
            return string.Empty;
        }

        var returnType = GetReturnType(method, includeTask: true, includeAuth: false);
        var parameters = GetParameterDeclarationsWithOptionalCancellationToken(method.Parameters, includeServices: false);

        var prefix = needsInternalPrefix ? "internal " : "";
        var result = $"{prefix}{returnType} {method.Name}({parameters});";

        // For Save methods with auth, also add TrySave interface method
        if (method is SaveMethodModel sm && sm.HasAuth)
        {
            var authReturnType = GetReturnType(method, includeTask: true, includeAuth: true);
            result += $"\n        {prefix}{authReturnType} Try{method.Name}({parameters});";
        }

        return result;
    }

    private static void RenderFactoryClass(StringBuilder sb, ClassFactoryModel model, FactoryMode mode)
    {
        // Factory pipeline is inlined directly into the generated class.
        var implementsInterfaces = model.HasDefaultSave
            ? $"IFactorySave<{model.ImplementationTypeName}>, I{model.ImplementationTypeName}Factory"
            : $"I{model.ImplementationTypeName}Factory";

        sb.AppendLine($"    internal class {model.ImplementationTypeName}Factory : {implementsInterfaces}");
        sb.AppendLine("    {");

        // Fields
        sb.AppendLine("        private readonly IServiceProvider ServiceProvider;");

        if (mode == FactoryMode.RemoteOnly)
        {
            sb.AppendLine("        private readonly IMakeRemoteDelegateRequest MakeRemoteDelegateRequest;");
        }
        else
        {
            sb.AppendLine("        private readonly IMakeRemoteDelegateRequest? MakeRemoteDelegateRequest;");
        }

        sb.AppendLine();

        // Delegates
        sb.AppendLine("        // Delegates");
        foreach (var method in model.Methods.Where(m => m.IsRemote && !(m is WriteMethodModel)))
        {
            RenderDelegate(sb, method);
        }
        sb.AppendLine();

        // Delegate properties
        sb.AppendLine("        // Delegate Properties to provide Local or Remote fork in execution");
        foreach (var method in model.Methods.Where(m => m.IsRemote && !(m is WriteMethodModel)))
        {
            RenderDelegateProperty(sb, method);
        }
        sb.AppendLine();

        // Constructors
        RenderConstructors(sb, model, mode);

        // Methods
        foreach (var method in model.Methods)
        {
            if (method is WriteMethodModel wm)
            {
                // Write methods only get LocalMethod generated (in Full mode)
                if (mode == FactoryMode.Full || !method.IsRemote)
                {
                    RenderLocalMethod(sb, wm, model, mode);
                }
            }
            else if (method is SaveMethodModel sm)
            {
                RenderSaveMethod(sb, sm, model, mode);
            }
            else if (method is ClassExecuteMethodModel em)
            {
                RenderClassExecuteMethod(sb, em, model, mode);
            }
            else if (method is ReadMethodModel rm)
            {
                RenderReadMethod(sb, rm, model, mode);
            }
            else if (method is CanMethodModel cm)
            {
                RenderCanMethod(sb, cm, model, mode);
            }
        }

        // FactoryServiceRegistrar
        RenderFactoryServiceRegistrar(sb, model, mode);

        sb.AppendLine("    }");
    }

    #region Delegate Rendering

    private static void RenderDelegate(StringBuilder sb, FactoryMethodModel method)
    {
        var returnType = GetReturnType(method, includeTask: true, includeAuth: true);
        // Delegate signature excludes services - they're injected in LocalMethod
        var parameters = GetParameterDeclarationsWithOptionalCancellationToken(method.Parameters, includeServices: false);

        sb.AppendLine($"        public delegate {returnType} {method.UniqueName}Delegate({parameters});");
    }

    private static void RenderDelegateProperty(StringBuilder sb, FactoryMethodModel method)
    {
        sb.AppendLine($"        public {method.UniqueName}Delegate {method.UniqueName}Property {{ get; }}");
    }

    #endregion

    #region Constructor Rendering

    private static void RenderConstructors(StringBuilder sb, ClassFactoryModel model, FactoryMode mode)
    {
        if (mode == FactoryMode.RemoteOnly)
        {
            // RemoteOnly mode: Only generate remote constructor
            sb.AppendLine($"        public {model.ImplementationTypeName}Factory(IServiceProvider serviceProvider, IMakeRemoteDelegateRequest remoteMethodDelegate)");
            sb.AppendLine("        {");
            sb.AppendLine("            this.ServiceProvider = serviceProvider;");
            sb.AppendLine("            this.MakeRemoteDelegateRequest = remoteMethodDelegate;");

            // Remote property assignments
            foreach (var method in model.Methods.Where(m => m.IsRemote && !(m is WriteMethodModel)))
            {
                sb.AppendLine($"            {method.UniqueName}Property = Remote{method.UniqueName};");
            }

            sb.AppendLine("        }");
        }
        else
        {
            // Full mode: Generate both constructors
            // Local constructor
            sb.AppendLine($"        public {model.ImplementationTypeName}Factory(IServiceProvider serviceProvider)");
            sb.AppendLine("        {");
            sb.AppendLine("            this.ServiceProvider = serviceProvider;");

            // Local property assignments
            foreach (var method in model.Methods.Where(m => m.IsRemote && !(m is WriteMethodModel)))
            {
                sb.AppendLine($"            {method.UniqueName}Property = Local{method.UniqueName};");
            }

            sb.AppendLine("        }");
            sb.AppendLine();

            // Remote constructor
            sb.AppendLine($"        public {model.ImplementationTypeName}Factory(IServiceProvider serviceProvider, IMakeRemoteDelegateRequest remoteMethodDelegate)");
            sb.AppendLine("        {");
            sb.AppendLine("            this.ServiceProvider = serviceProvider;");
            sb.AppendLine("            this.MakeRemoteDelegateRequest = remoteMethodDelegate;");

            // Remote property assignments
            foreach (var method in model.Methods.Where(m => m.IsRemote && !(m is WriteMethodModel)))
            {
                sb.AppendLine($"            {method.UniqueName}Property = Remote{method.UniqueName};");
            }

            sb.AppendLine("        }");
        }

        sb.AppendLine();
    }

    #endregion

    #region Read Method Rendering

    private static void RenderReadMethod(StringBuilder sb, ReadMethodModel method, ClassFactoryModel model, FactoryMode mode)
    {
        // Public method
        RenderPublicMethod(sb, method);

        // Remote method (if remote)
        if (method.IsRemote)
        {
            RenderRemoteMethod(sb, method);
        }

        // Local method (in Full mode, or for non-remote methods)
        if (mode == FactoryMode.Full || !method.IsRemote)
        {
            RenderReadLocalMethod(sb, method, model);
        }
    }

    private static void RenderPublicMethod(StringBuilder sb, FactoryMethodModel method)
    {
        var hasAuth = method.HasAuth;
        var asyncKeyword = method.IsTask && hasAuth ? "async" : "";
        var awaitKeyword = method.IsTask && hasAuth ? "await" : "";
        var returnType = GetReturnType(method, includeTask: true, includeAuth: false);
        var parameters = GetParameterDeclarationsWithOptionalCancellationToken(method.Parameters, includeServices: false);
        var paramIdentifiers = GetParameterIdentifiersWithCancellationToken(method.Parameters, includeServices: false);

        sb.AppendLine($"        public virtual {asyncKeyword} {returnType} {method.Name}({parameters})");
        sb.AppendLine("        {");

        var methodTarget = method.IsRemote ? $"{method.UniqueName}Property" : $"Local{method.UniqueName}";

        if (!hasAuth)
        {
            sb.AppendLine($"            return {methodTarget}({paramIdentifiers});");
        }
        else
        {
            sb.AppendLine($"            return ({awaitKeyword} {methodTarget}({paramIdentifiers})).Result;");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void RenderRemoteMethod(StringBuilder sb, FactoryMethodModel method)
    {
        var returnType = GetReturnType(method, includeTask: true, includeAuth: true);
        var returnTypeWithoutTask = GetReturnType(method, includeTask: false, includeAuth: true);
        // Remote method signature excludes services
        var parameters = GetParameterDeclarationsWithOptionalCancellationToken(method.Parameters, includeServices: false);
        var nullableText = returnTypeWithoutTask.EndsWith("?") ? "Nullable" : "";

        // Exclude CancellationToken from serialized parameters
        var serializedParams = string.Join(", ", method.Parameters
            .Where(p => !p.IsService && !p.IsCancellationToken)
            .Select(p => p.Name));

        sb.AppendLine($"        public virtual async {returnType} Remote{method.UniqueName}({parameters})");
        sb.AppendLine("        {");
        sb.AppendLine($"            return (await MakeRemoteDelegateRequest!.ForDelegate{nullableText}<{returnTypeWithoutTask}>(typeof({method.UniqueName}Delegate), [{serializedParams}], cancellationToken))!;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void RenderReadLocalMethod(StringBuilder sb, ReadMethodModel method, ClassFactoryModel model)
    {
        // Use async when the method uses await: domain method returns Task,
        // or the original factory method was async, or auth checks need await
        var needsAsync = method.IsAsync || method.IsDomainMethodTask;
        var asyncKeyword = needsAsync ? "async" : "";
        var returnType = GetReturnType(method, includeTask: true, includeAuth: true);
        // Local method signature excludes services - they're obtained via ServiceProvider inside
        var parameters = GetParameterDeclarationsWithOptionalCancellationToken(method.Parameters, includeServices: false);

        sb.AppendLine($"        public {asyncKeyword} {returnType} Local{method.UniqueName}({parameters})");
        sb.AppendLine("        {");

        // Feature switch guard -- only emit for internal or [Remote] methods.
        // Public non-[Remote] methods run on both client and server.
        if (method.IsInternal || method.IsRemote)
        {
            sb.AppendLine("            if (!NeatooRuntime.IsServerRuntime)");
            sb.AppendLine("                throw new InvalidOperationException(\"Server-only method called in non-server runtime.\");");
            sb.AppendLine();
        }

        // Authorization checks (inside guard -- auth types are server-only)
        RenderAuthorizationChecks(sb, method);

        // Determine if this is a "read-style" (constructor/static factory) or "write-style" (instance target) invocation.
        // Constructor/static factory: Read lifecycle (only IFactoryOnComplete on result)
        // Instance method with target: Write lifecycle (IFactoryOnStart before, IFactoryOnComplete after, etc.)
        var isWriteStyleLifecycle = !method.IsConstructor && !method.IsStaticFactory;

        // Inline factory pipeline: logger, correlation, stopwatch
        sb.AppendLine($"            var _logger = ServiceProvider.GetService<ILogger<{model.ImplementationTypeName}Factory>>();");
        sb.AppendLine("            var _correlationContext = ServiceProvider.GetService<ICorrelationContext>();");
        sb.AppendLine("            var _correlationId = _correlationContext?.CorrelationId;");
        EmitLogOperationStarted(sb, "            ", method.Operation, model.ServiceTypeName);
        sb.AppendLine("            var _sw = System.Diagnostics.Stopwatch.StartNew();");
        sb.AppendLine();

        // Get target if not constructor or static factory
        if (isWriteStyleLifecycle)
        {
            sb.AppendLine($"            var target = ServiceProvider.GetRequiredService<{model.ImplementationTypeName}>();");
        }

        // Service assignments
        RenderServiceAssignments(sb, method.Parameters);

        sb.AppendLine("            try");
        sb.AppendLine("            {");

        // For write-style lifecycle: IFactoryOnStart before method call
        if (isWriteStyleLifecycle)
        {
            RenderWriteLifecycleOnStart(sb, method.IsDomainMethodTask, model, "target", method.Operation);
        }

        // Build domain method invocation
        var domainParams = GetParameterIdentifiersForDomainInvocation(method.Parameters);

        if (method.IsConstructor)
        {
            // Constructor: result is the new instance
            if (method.IsDomainMethodTask)
            {
                // Async constructor is not possible in C#, but the model might represent it via Task
                sb.AppendLine($"                var _result = await new {model.ImplementationTypeName}({domainParams});");
            }
            else
            {
                sb.AppendLine($"                var _result = new {model.ImplementationTypeName}({domainParams});");
            }
        }
        else if (method.IsStaticFactory)
        {
            if (method.IsDomainMethodTask)
            {
                sb.AppendLine($"                var _result = await {model.ImplementationTypeName}.{method.Name}({domainParams});");
            }
            else
            {
                sb.AppendLine($"                var _result = {model.ImplementationTypeName}.{method.Name}({domainParams});");
            }
        }
        else
        {
            // Instance method on target -- the domain method may return void/Task (mutates target)
            // or return bool/Task<bool>
            if (method.IsBool)
            {
                if (method.IsDomainMethodTask)
                {
                    sb.AppendLine($"                var _succeeded = await target.{method.Name}({domainParams});");
                }
                else
                {
                    sb.AppendLine($"                var _succeeded = target.{method.Name}({domainParams});");
                }
            }
            else if (method.IsDomainMethodTask)
            {
                sb.AppendLine($"                await target.{method.Name}({domainParams});");
            }
            else
            {
                sb.AppendLine($"                target.{method.Name}({domainParams});");
            }
        }

        // Bool check: if domain method returned false, return default without calling IFactoryOnComplete
        if (method.IsBool && !method.IsConstructor && !method.IsStaticFactory)
        {
            sb.AppendLine("                if (!_succeeded)");
            sb.AppendLine("                {");
            sb.AppendLine("                    _sw.Stop();");
            EmitLogOperationCompleted(sb, "                    ", method.Operation, model.ServiceTypeName);
            // For non-async methods returning Task, wrap default in Task.FromResult to avoid null Task.
            // Use null-forgiving operator (!) when returning default for non-nullable return types
            // (e.g., Authorized<T>), matching original DoFactoryMethodCallBool behavior.
            if (!needsAsync && method.IsTask)
            {
                var nullableServiceType = method.IsNullable ? $"{model.ServiceTypeName}?" : model.ServiceTypeName;
                sb.AppendLine($"                    return Task.FromResult<{nullableServiceType}>(default)!;");
            }
            else
            {
                sb.AppendLine("                    return default!;");
            }
            sb.AppendLine("                }");
        }

        // Determine the result variable for IFactoryOnComplete and return
        string resultVar;
        if (method.IsConstructor || method.IsStaticFactory)
        {
            resultVar = "_result";
        }
        else
        {
            resultVar = "target";
        }

        // IFactoryOnComplete check -- on result for read-style, on target for write-style
        if (isWriteStyleLifecycle)
        {
            RenderWriteLifecycleOnComplete(sb, method.IsDomainMethodTask, model, "target", method.Operation);
        }
        else
        {
            // Read-style: only IFactoryOnComplete (sync) on the result
            if (method.IsDomainMethodNullable)
            {
                sb.AppendLine($"                if ({resultVar} is IFactoryOnComplete _factoryOnComplete)");
            }
            else
            {
                sb.AppendLine($"                if ({resultVar} is IFactoryOnComplete _factoryOnComplete)");
            }
            sb.AppendLine("                {");
            EmitLogInvokingOnComplete(sb, "                    ", model.ServiceTypeName);
            sb.AppendLine($"                    _factoryOnComplete.FactoryComplete(FactoryOperation.{method.Operation});");
            sb.AppendLine("                }");
        }

        sb.AppendLine("                _sw.Stop();");
        EmitLogOperationCompleted(sb, "                ", method.Operation, model.ServiceTypeName);

        // Build return value -- cast to ServiceTypeName if it differs from ImplementationTypeName
        // (e.g., IOrder vs Order) to ensure correct Task<T> type inference
        var returnExpr = model.ServiceTypeName != model.ImplementationTypeName
            ? $"({model.ServiceTypeName}) {resultVar}"
            : resultVar;
        if (method.HasAuth)
        {
            returnExpr = $"new Authorized<{model.ServiceTypeName}>({returnExpr})";
        }
        // Wrap in Task.FromResult if domain method doesn't return Task but factory method needs to
        if (!method.IsDomainMethodTask && method.IsTask && !method.IsAsync)
        {
            // Use explicit type argument when nullable to avoid Task<T> vs Task<T?> mismatch
            if (method.IsNullable && !method.HasAuth)
            {
                returnExpr = $"Task.FromResult<{model.ServiceTypeName}?>({returnExpr})";
            }
            else
            {
                returnExpr = $"Task.FromResult({returnExpr})";
            }
        }
        sb.AppendLine($"                return {returnExpr};");

        sb.AppendLine("            }");

        // For write-style async methods: catch OperationCanceledException
        if (isWriteStyleLifecycle && method.IsDomainMethodTask)
        {
            RenderWriteLifecycleOnCancelled(sb, method, model, resultVar);
        }

        // Catch general exceptions
        sb.AppendLine("            catch (Exception _ex)");
        sb.AppendLine("            {");
        sb.AppendLine("                _sw.Stop();");
        EmitLogOperationFailed(sb, "                ", method.Operation, model.ServiceTypeName);
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    #endregion

    #region Inline Pipeline Log Helpers

    /// <summary>
    /// Emits a log call for factory operation started.
    /// </summary>
    private static void EmitLogOperationStarted(StringBuilder sb, string indent, FactoryOperation operation, string typeName)
    {
        sb.Append(indent);
        sb.Append("_logger?.LogInformation(\"[{CorrelationId}] Factory operation {Operation} started for {TypeName}\", _correlationId, FactoryOperation.");
        sb.Append(operation);
        sb.Append(", \"");
        sb.Append(typeName);
        sb.AppendLine("\");");
    }

    /// <summary>
    /// Emits a log call for factory operation completed.
    /// </summary>
    private static void EmitLogOperationCompleted(StringBuilder sb, string indent, FactoryOperation operation, string typeName)
    {
        sb.Append(indent);
        sb.Append("_logger?.LogInformation(\"[{CorrelationId}] Factory operation {Operation} completed for {TypeName} in {ElapsedMs}ms\", _correlationId, FactoryOperation.");
        sb.Append(operation);
        sb.Append(", \"");
        sb.Append(typeName);
        sb.AppendLine("\", _sw.ElapsedMilliseconds);");
    }

    /// <summary>
    /// Emits a log call for factory operation failed.
    /// </summary>
    private static void EmitLogOperationFailed(StringBuilder sb, string indent, FactoryOperation operation, string typeName)
    {
        sb.Append(indent);
        sb.Append("_logger?.LogError(_ex, \"[{CorrelationId}] Factory operation {Operation} failed for {TypeName}: {ErrorMessage}\", _correlationId, FactoryOperation.");
        sb.Append(operation);
        sb.Append(", \"");
        sb.Append(typeName);
        sb.AppendLine("\", _ex.Message);");
    }

    /// <summary>
    /// Emits a log call for factory operation cancelled.
    /// </summary>
    private static void EmitLogOperationCancelled(StringBuilder sb, string indent, FactoryOperation operation, string typeName)
    {
        sb.Append(indent);
        sb.Append("_logger?.LogInformation(\"[{CorrelationId}] Factory operation {Operation} cancelled for {TypeName}\", _correlationId, FactoryOperation.");
        sb.Append(operation);
        sb.Append(", \"");
        sb.Append(typeName);
        sb.AppendLine("\");");
    }

    /// <summary>
    /// Emits a log call for invoking IFactoryOnStart.
    /// </summary>
    private static void EmitLogInvokingOnStart(StringBuilder sb, string indent, string typeName)
    {
        sb.Append(indent);
        sb.Append("_logger?.LogDebug(\"Invoking IFactoryOnStart for {TypeName}\", \"");
        sb.Append(typeName);
        sb.AppendLine("\");");
    }

    /// <summary>
    /// Emits a log call for invoking IFactoryOnComplete.
    /// </summary>
    private static void EmitLogInvokingOnComplete(StringBuilder sb, string indent, string typeName)
    {
        sb.Append(indent);
        sb.Append("_logger?.LogDebug(\"Invoking IFactoryOnComplete for {TypeName}\", \"");
        sb.Append(typeName);
        sb.AppendLine("\");");
    }

    /// <summary>
    /// Emits a log call for invoking IFactoryOnCancelled.
    /// </summary>
    private static void EmitLogInvokingOnCancelled(StringBuilder sb, string indent, string typeName)
    {
        sb.Append(indent);
        sb.Append("_logger?.LogDebug(\"Invoking IFactoryOnCancelled for {TypeName}\", \"");
        sb.Append(typeName);
        sb.AppendLine("\");");
    }

    #endregion

    #region Inline Pipeline Lifecycle Helpers

    /// <summary>
    /// Renders IFactoryOnStart and IFactoryOnStartAsync checks (Write lifecycle, before method call).
    /// Only the async Write variant includes IFactoryOnStartAsync.
    /// </summary>
    private static void RenderWriteLifecycleOnStart(StringBuilder sb, bool isDomainMethodTask, ClassFactoryModel model, string targetVar, FactoryOperation operation)
    {
        sb.AppendLine($"                if ({targetVar} is IFactoryOnStart _factoryOnStart)");
        sb.AppendLine("                {");
        EmitLogInvokingOnStart(sb, "                    ", model.ServiceTypeName);
        sb.AppendLine($"                    _factoryOnStart.FactoryStart(FactoryOperation.{operation});");
        sb.AppendLine("                }");

        // Async start hook only for async domain methods
        if (isDomainMethodTask)
        {
            sb.AppendLine($"                if ({targetVar} is IFactoryOnStartAsync _factoryOnStartAsync)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    await _factoryOnStartAsync.FactoryStartAsync(FactoryOperation.{operation});");
            sb.AppendLine("                }");
        }
    }

    /// <summary>
    /// Renders IFactoryOnComplete and IFactoryOnCompleteAsync checks (Write lifecycle, after method call).
    /// Only the async Write variant includes IFactoryOnCompleteAsync.
    /// </summary>
    private static void RenderWriteLifecycleOnComplete(StringBuilder sb, bool isDomainMethodTask, ClassFactoryModel model, string targetVar, FactoryOperation operation)
    {
        sb.AppendLine($"                if ({targetVar} is IFactoryOnComplete _factoryOnComplete)");
        sb.AppendLine("                {");
        EmitLogInvokingOnComplete(sb, "                    ", model.ServiceTypeName);
        sb.AppendLine($"                    _factoryOnComplete.FactoryComplete(FactoryOperation.{operation});");
        sb.AppendLine("                }");

        // Async complete hook only for async domain methods
        if (isDomainMethodTask)
        {
            sb.AppendLine($"                if ({targetVar} is IFactoryOnCompleteAsync _factoryOnCompleteAsync)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    await _factoryOnCompleteAsync.FactoryCompleteAsync(FactoryOperation.{operation});");
            sb.AppendLine("                }");
        }
    }

    /// <summary>
    /// Renders OperationCanceledException catch block with IFactoryOnCancelled hooks (async Write lifecycle only).
    /// </summary>
    private static void RenderWriteLifecycleOnCancelled(StringBuilder sb, FactoryMethodModel method, ClassFactoryModel model, string targetVar)
    {
        sb.AppendLine("            catch (OperationCanceledException)");
        sb.AppendLine("            {");
        sb.AppendLine("                _sw.Stop();");
        EmitLogOperationCancelled(sb, "                ", method.Operation, model.ServiceTypeName);
        sb.AppendLine($"                if ({targetVar} is IFactoryOnCancelled _factoryOnCancelled)");
        sb.AppendLine("                {");
        EmitLogInvokingOnCancelled(sb, "                    ", model.ServiceTypeName);
        sb.AppendLine($"                    _factoryOnCancelled.FactoryCancelled(FactoryOperation.{method.Operation});");
        sb.AppendLine("                }");
        sb.AppendLine($"                if ({targetVar} is IFactoryOnCancelledAsync _factoryOnCancelledAsync)");
        sb.AppendLine("                {");
        sb.AppendLine($"                    await _factoryOnCancelledAsync.FactoryCancelledAsync(FactoryOperation.{method.Operation});");
        sb.AppendLine("                }");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
    }

    #endregion

    #region Class Execute Method Rendering

    private static void RenderClassExecuteMethod(
        StringBuilder sb, ClassExecuteMethodModel method,
        ClassFactoryModel model, FactoryMode mode)
    {
        // Public method (delegates to local or remote)
        RenderClassExecutePublicMethod(sb, method);

        // Remote method
        if (method.IsRemote)
        {
            RenderRemoteMethod(sb, method);
        }

        // Local method (in Full mode, or for non-remote methods)
        if (mode == FactoryMode.Full || !method.IsRemote)
        {
            RenderClassExecuteLocalMethod(sb, method, model);
        }
    }

    private static void RenderClassExecutePublicMethod(StringBuilder sb, ClassExecuteMethodModel method)
    {
        var hasAuth = method.HasAuth;
        var asyncKeyword = method.IsTask && hasAuth ? "async" : "";
        var awaitKeyword = method.IsTask && hasAuth ? "await" : "";
        var returnType = GetReturnType(method, includeTask: true, includeAuth: false);
        var parameters = GetParameterDeclarationsWithOptionalCancellationToken(method.Parameters, includeServices: false);
        var paramIdentifiers = GetParameterIdentifiersWithCancellationToken(method.Parameters, includeServices: false);

        sb.AppendLine($"        public virtual {asyncKeyword} {returnType} {method.Name}({parameters})");
        sb.AppendLine("        {");

        var methodTarget = method.IsRemote ? $"{method.UniqueName}Property" : $"Local{method.UniqueName}";

        if (!hasAuth)
        {
            sb.AppendLine($"            return {methodTarget}({paramIdentifiers});");
        }
        else
        {
            sb.AppendLine($"            return ({awaitKeyword} {methodTarget}({paramIdentifiers})).Result;");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void RenderClassExecuteLocalMethod(
        StringBuilder sb, ClassExecuteMethodModel method,
        ClassFactoryModel model)
    {
        var returnType = GetReturnType(method, includeTask: true, includeAuth: true);
        var parameters = GetParameterDeclarationsWithOptionalCancellationToken(method.Parameters, includeServices: false);

        sb.AppendLine($"        public async {returnType} Local{method.UniqueName}({parameters})");
        sb.AppendLine("        {");

        // Feature switch guard -- only emit for internal or [Remote] methods.
        // Public non-[Remote] methods run on both client and server.
        if (method.IsInternal || method.IsRemote)
        {
            sb.AppendLine("            if (!NeatooRuntime.IsServerRuntime)");
            sb.AppendLine("                throw new InvalidOperationException(\"Server-only method called in non-server runtime.\");");
            sb.AppendLine();
        }

        // Authorization checks (inside guard -- auth types are server-only)
        RenderAuthorizationChecks(sb, method);

        // Service assignments
        foreach (var sp in method.ServiceParameters)
        {
            sb.AppendLine($"            var {sp.Name} = ServiceProvider.GetRequiredService<{sp.Type}>();");
        }

        // Build invocation parameters: data params, then services, then CT if present
        var allParams = new List<string>();
        allParams.AddRange(method.Parameters.Select(p => p.Name));
        allParams.AddRange(method.ServiceParameters.Select(p => p.Name));
        if (method.HasCancellationToken)
        {
            allParams.Add("cancellationToken");
        }
        var paramList = string.Join(", ", allParams);

        // Call the static method directly on the implementation type
        var methodCall = $"{model.ImplementationTypeName}.{method.Name}({paramList})";

        if (method.HasAuth)
        {
            sb.AppendLine($"            var result = await {methodCall};");
            sb.AppendLine($"            return new Authorized<{model.ServiceTypeName}>(result);");
        }
        else
        {
            sb.AppendLine($"            return await {methodCall};");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    #endregion

    #region Write Method Rendering

    private static void RenderLocalMethod(StringBuilder sb, WriteMethodModel method, ClassFactoryModel model, FactoryMode mode)
    {
        // Use async when the method uses await: domain method returns Task,
        // or the original factory method was async
        var needsAsync = method.IsAsync || method.IsDomainMethodTask;
        var asyncKeyword = needsAsync ? "async" : "";
        var returnType = GetReturnType(method, includeTask: true, includeAuth: true);
        // Local method signature excludes services - they're obtained via ServiceProvider inside
        var parameters = GetParameterDeclarationsWithOptionalCancellationToken(method.Parameters, includeServices: false);

        sb.AppendLine($"        public {asyncKeyword} {returnType} Local{method.UniqueName}({parameters})");
        sb.AppendLine("        {");

        // Feature switch guard -- only emit for internal or [Remote] methods.
        // Public non-[Remote] methods run on both client and server.
        if (method.IsInternal || method.IsRemote)
        {
            sb.AppendLine("            if (!NeatooRuntime.IsServerRuntime)");
            sb.AppendLine("                throw new InvalidOperationException(\"Server-only method called in non-server runtime.\");");
            sb.AppendLine();
        }

        // Authorization checks (inside guard -- auth types are server-only)
        RenderAuthorizationChecks(sb, method);

        // Cast target to implementation type
        sb.AppendLine($"            var cTarget = ({model.ImplementationTypeName}) target ?? throw new Exception(\"{model.ServiceTypeName} must implement {model.ImplementationTypeName}\");");

        // Inline factory pipeline: logger, correlation, stopwatch
        sb.AppendLine($"            var _logger = ServiceProvider.GetService<ILogger<{model.ImplementationTypeName}Factory>>();");
        sb.AppendLine("            var _correlationContext = ServiceProvider.GetService<ICorrelationContext>();");
        sb.AppendLine("            var _correlationId = _correlationContext?.CorrelationId;");
        EmitLogOperationStarted(sb, "            ", method.Operation, model.ServiceTypeName);
        sb.AppendLine("            var _sw = System.Diagnostics.Stopwatch.StartNew();");
        sb.AppendLine();

        // Service assignments
        RenderServiceAssignments(sb, method.Parameters);

        sb.AppendLine("            try");
        sb.AppendLine("            {");

        // IFactoryOnStart before method call (Write lifecycle)
        RenderWriteLifecycleOnStart(sb, method.IsDomainMethodTask, model, "cTarget", method.Operation);

        // Build domain method invocation
        var domainParams = GetParameterIdentifiersForDomainInvocation(method.Parameters);

        if (method.IsBool)
        {
            if (method.IsDomainMethodTask)
            {
                sb.AppendLine($"                var _succeeded = await cTarget.{method.Name}({domainParams});");
            }
            else
            {
                sb.AppendLine($"                var _succeeded = cTarget.{method.Name}({domainParams});");
            }

            // Bool check: if domain method returned false, return default without calling IFactoryOnComplete
            sb.AppendLine("                if (!_succeeded)");
            sb.AppendLine("                {");
            sb.AppendLine("                    _sw.Stop();");
            EmitLogOperationCompleted(sb, "                    ", method.Operation, model.ServiceTypeName);
            // For non-async methods returning Task, wrap default in Task.FromResult to avoid null Task.
            // Use null-forgiving operator (!) when returning default for non-nullable return types
            // (e.g., Authorized<T>), matching original DoFactoryMethodCallBool behavior.
            if (!needsAsync && method.IsTask)
            {
                var nullableServiceType = method.IsNullable ? $"{model.ServiceTypeName}?" : model.ServiceTypeName;
                sb.AppendLine($"                    return Task.FromResult<{nullableServiceType}>(default)!;");
            }
            else
            {
                sb.AppendLine("                    return default!;");
            }
            sb.AppendLine("                }");
        }
        else
        {
            if (method.IsDomainMethodTask)
            {
                sb.AppendLine($"                await cTarget.{method.Name}({domainParams});");
            }
            else
            {
                sb.AppendLine($"                cTarget.{method.Name}({domainParams});");
            }
        }

        // IFactoryOnComplete after method call (Write lifecycle)
        RenderWriteLifecycleOnComplete(sb, method.IsDomainMethodTask, model, "cTarget", method.Operation);

        sb.AppendLine("                _sw.Stop();");
        EmitLogOperationCompleted(sb, "                ", method.Operation, model.ServiceTypeName);

        // Build return value -- cast to ServiceTypeName if it differs from ImplementationTypeName
        // (e.g., IOrder vs Order) to ensure correct Task<T> type inference
        var returnExpr = model.ServiceTypeName != model.ImplementationTypeName
            ? $"({model.ServiceTypeName}) cTarget"
            : "cTarget";
        if (method.HasAuth)
        {
            returnExpr = $"new Authorized<{model.ServiceTypeName}>({returnExpr})";
        }
        // Wrap in Task.FromResult if domain method doesn't return Task but factory method needs to
        if (!method.IsDomainMethodTask && method.IsTask && !method.IsAsync)
        {
            // Use explicit type argument when nullable to avoid Task<T> vs Task<T?> mismatch
            if (method.IsNullable && !method.HasAuth)
            {
                returnExpr = $"Task.FromResult<{model.ServiceTypeName}?>({returnExpr})";
            }
            else
            {
                returnExpr = $"Task.FromResult({returnExpr})";
            }
        }
        sb.AppendLine($"                return {returnExpr};");

        sb.AppendLine("            }");

        // For async Write methods: catch OperationCanceledException
        if (method.IsDomainMethodTask)
        {
            RenderWriteLifecycleOnCancelled(sb, method, model, "cTarget");
        }

        // Catch general exceptions
        sb.AppendLine("            catch (Exception _ex)");
        sb.AppendLine("            {");
        sb.AppendLine("                _sw.Stop();");
        EmitLogOperationFailed(sb, "                ", method.Operation, model.ServiceTypeName);
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    #endregion

    #region Save Method Rendering

    private static void RenderSaveMethod(StringBuilder sb, SaveMethodModel method, ClassFactoryModel model, FactoryMode mode)
    {
        // Public method (with auth handling)
        RenderSavePublicMethod(sb, method, model);

        // Remote method (if remote)
        if (method.IsRemote)
        {
            RenderRemoteMethod(sb, method);
        }

        // Local method (in Full mode, or for non-remote methods)
        if (mode == FactoryMode.Full || !method.IsRemote)
        {
            RenderSaveLocalMethod(sb, method, model);
        }

        // Explicit interface method (always needed)
        RenderSaveExplicitInterfaceMethod(sb, method, model);

        // CanSave explicit interface method (for IFactorySave<T>.CanSave)
        RenderCanSaveExplicitInterfaceMethod(sb, method, model);
    }

    private static void RenderSavePublicMethod(StringBuilder sb, SaveMethodModel method, ClassFactoryModel model)
    {
        var hasAuth = method.HasAuth;
        var returnType = GetReturnType(method, includeTask: true, includeAuth: false);
        // Public method excludes services - they're injected in the local method
        var parameters = GetParameterDeclarationsWithOptionalCancellationToken(method.Parameters, includeServices: false);
        var paramIdentifiers = GetParameterIdentifiersWithCancellationToken(method.Parameters, includeServices: false);

        var methodTarget = method.IsRemote ? $"{method.UniqueName}Property" : $"Local{method.UniqueName}";

        if (!hasAuth)
        {
            var asyncKeyword = method.IsTask ? "" : "";
            sb.AppendLine($"        public virtual {asyncKeyword} {returnType} {method.Name}({parameters})");
            sb.AppendLine("        {");
            sb.AppendLine($"            return {methodTarget}({paramIdentifiers});");
            sb.AppendLine("        }");
        }
        else
        {
            var asyncKeyword = method.IsTask ? "async" : "";
            var awaitKeyword = method.IsTask ? "await" : "";

            sb.AppendLine($"        public virtual {asyncKeyword} {returnType} {method.Name}({parameters})");
            sb.AppendLine("        {");
            sb.AppendLine($"            var authorized = ({awaitKeyword} {methodTarget}({paramIdentifiers}));");
            sb.AppendLine("            if (!authorized.HasAccess)");
            sb.AppendLine("            {");
            sb.AppendLine("                throw new NotAuthorizedException(authorized);");
            sb.AppendLine("            }");
            sb.AppendLine("            return authorized.Result;");
            sb.AppendLine("        }");
            sb.AppendLine();

            // TrySave method
            var authReturnType = GetReturnType(method, includeTask: true, includeAuth: true);
            var asyncKeyword2 = method.IsAsync ? "async" : "";
            var awaitKeyword2 = method.IsAsync ? "await" : "";

            sb.AppendLine($"        public virtual {asyncKeyword2} {authReturnType} Try{method.Name}({parameters})");
            sb.AppendLine("        {");
            sb.AppendLine($"            return {awaitKeyword2} {methodTarget}({paramIdentifiers});");
            sb.AppendLine("        }");
        }

        sb.AppendLine();
    }

    private static void RenderSaveLocalMethod(StringBuilder sb, SaveMethodModel method, ClassFactoryModel model)
    {
        var asyncKeyword = method.IsAsync ? "async" : "";
        var returnType = GetReturnType(method, includeTask: true, includeAuth: true);
        // Local method signature excludes services - they're obtained via ServiceProvider inside
        var parameters = GetParameterDeclarationsWithOptionalCancellationToken(method.Parameters, includeServices: false);
        var paramIdentifiers = GetParameterIdentifiersWithCancellationToken(method.Parameters, includeServices: false);

        sb.AppendLine($"        public virtual {asyncKeyword} {returnType} Local{method.UniqueName}({parameters})");
        sb.AppendLine("        {");

        // Feature switch guard -- only emit for internal or [Remote] methods.
        // Public non-[Remote] methods run on both client and server.
        if (method.IsInternal || method.IsRemote)
        {
            sb.AppendLine("            if (!NeatooRuntime.IsServerRuntime)");
            sb.AppendLine("                throw new InvalidOperationException(\"Server-only method called in non-server runtime.\");");
        }
        sb.AppendLine();

        // Default return value
        var defaultReturn = method.HasAuth
            ? $"new Authorized<{model.ServiceTypeName}>()"
            : $"default({model.ServiceTypeName})";

        if (method.IsTask && !method.IsAsync)
        {
            defaultReturn = $"Task.FromResult({defaultReturn})";
        }

        // Delete branch
        sb.AppendLine("            if (target.IsDeleted)");
        sb.AppendLine("            {");
        if (method.DeleteMethod != null)
        {
            var deleteCall = BuildSaveBranchCall(method, method.DeleteMethod, paramIdentifiers);
            sb.AppendLine($"                if (target.IsNew) {{ return {defaultReturn}; }}");
            sb.AppendLine($"                return {deleteCall};");
        }
        else
        {
            sb.AppendLine("                throw new NotImplementedException();");
        }
        sb.AppendLine("            }");

        // Insert branch
        sb.AppendLine("            else if (target.IsNew)");
        sb.AppendLine("            {");
        if (method.InsertMethod != null)
        {
            var insertCall = BuildSaveBranchCall(method, method.InsertMethod, paramIdentifiers);
            sb.AppendLine($"                return {insertCall};");
        }
        else
        {
            sb.AppendLine("                throw new NotImplementedException();");
        }
        sb.AppendLine("            }");

        // Update branch
        sb.AppendLine("            else");
        sb.AppendLine("            {");
        if (method.UpdateMethod != null)
        {
            var updateCall = BuildSaveBranchCall(method, method.UpdateMethod, paramIdentifiers);
            sb.AppendLine($"                return {updateCall};");
        }
        else
        {
            sb.AppendLine("                throw new NotImplementedException();");
        }
        sb.AppendLine("            }");

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static string BuildSaveBranchCall(SaveMethodModel saveMethod, WriteMethodModel branchMethod, string _unused)
    {
        // Map branch method parameters to save method parameters
        // Branch method may have different parameter names but same types
        var branchParams = branchMethod.Parameters.Where(p => !p.IsService && !p.IsCancellationToken).ToList();
        var saveParams = saveMethod.Parameters.Where(p => !p.IsService && !p.IsCancellationToken).ToList();

        var paramList = new List<string>();

        // Add target
        if (branchMethod.Parameters.Any(p => p.IsTarget))
        {
            paramList.Add("target");
        }

        // Map branch method's non-target parameters to save method's parameters by position
        var branchNonTarget = branchParams.Where(p => !p.IsTarget).ToList();
        var saveNonTarget = saveParams.Where(p => !p.IsTarget).ToList();

        for (int i = 0; i < branchNonTarget.Count && i < saveNonTarget.Count; i++)
        {
            // Use save method's parameter name (which is in scope)
            paramList.Add(saveNonTarget[i].Name);
        }

        // Always add cancellation token - Local methods always have this parameter
        // (added by GetParameterDeclarationsWithOptionalCancellationToken)
        paramList.Add("cancellationToken");

        var methodCall = $"Local{branchMethod.UniqueName}({string.Join(", ", paramList)})";

        // Add await if save method is async AND branch method returns Task (IsTask, not IsDomainMethodTask)
        if (saveMethod.IsAsync && branchMethod.IsTask)
        {
            methodCall = $"await {methodCall}";
        }

        if (saveMethod.HasAuth && !branchMethod.HasAuth)
        {
            methodCall = $"new Authorized<{saveMethod.ServiceType}>({methodCall})";
        }

        // Wrap in Task.FromResult if branch local method doesn't return Task but save method needs to
        // Use branchMethod.IsTask (local method return type), not IsDomainMethodTask (domain method)
        if (!branchMethod.IsTask && saveMethod.IsTask && !saveMethod.IsAsync)
        {
            methodCall = $"Task.FromResult({methodCall})";
        }

        // Handle nullability mismatch: if save is nullable but branch isn't, add null-forgiving cast
        // This happens when SaveMethod.IsNullable (due to Delete) but WriteMethod.IsNullable is false
        if (saveMethod.IsNullable && !branchMethod.IsNullable && !saveMethod.HasAuth)
        {
            // Cast to nullable to satisfy the return type
            methodCall = $"({methodCall})!";
        }

        return methodCall;
    }

    private static void RenderSaveExplicitInterfaceMethod(StringBuilder sb, SaveMethodModel method, ClassFactoryModel model)
    {
        if (!method.IsDefault)
        {
            return;
        }

        sb.AppendLine($"        async Task<IFactorySaveMeta?> IFactorySave<{model.ImplementationTypeName}>.Save({model.ImplementationTypeName} target, CancellationToken cancellationToken)");
        sb.AppendLine("        {");

        if (method.IsTask)
        {
            sb.AppendLine($"            return (IFactorySaveMeta?) await {method.Name}(target, cancellationToken);");
        }
        else
        {
            sb.AppendLine($"            return await Task.FromResult((IFactorySaveMeta?) {method.Name}(target, cancellationToken));");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void RenderCanSaveExplicitInterfaceMethod(StringBuilder sb, SaveMethodModel method, ClassFactoryModel model)
    {
        if (!method.IsDefault)
        {
            return;
        }

        // Find the CanSave method that corresponds to this save method
        var canSaveMethod = model.Methods.OfType<CanMethodModel>()
            .FirstOrDefault(m => m.Name == $"Can{method.Name}");

        if (canSaveMethod == null)
        {
            // No auth configured -- generate default returning Authorized(true)
            sb.AppendLine($"        Task<Authorized> IFactorySave<{model.ImplementationTypeName}>.CanSave(CancellationToken cancellationToken)");
            sb.AppendLine("        {");
            sb.AppendLine("            return Task.FromResult(new Authorized(true));");
            sb.AppendLine("        }");
        }
        else
        {
            // Auth configured -- delegate to concrete CanSave method
            if (canSaveMethod.IsTask)
            {
                sb.AppendLine($"        async Task<Authorized> IFactorySave<{model.ImplementationTypeName}>.CanSave(CancellationToken cancellationToken)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return await {canSaveMethod.UniqueName}(cancellationToken);");
                sb.AppendLine("        }");
            }
            else
            {
                sb.AppendLine($"        Task<Authorized> IFactorySave<{model.ImplementationTypeName}>.CanSave(CancellationToken cancellationToken)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return Task.FromResult({canSaveMethod.UniqueName}(cancellationToken));");
                sb.AppendLine("        }");
            }
        }
        sb.AppendLine();
    }

    #endregion

    #region Can Method Rendering

    private static void RenderCanMethod(StringBuilder sb, CanMethodModel method, ClassFactoryModel model, FactoryMode mode)
    {
        var returnType = method.IsTask ? "Task<Authorized>" : "Authorized";
        var parameters = GetParameterDeclarationsWithOptionalCancellationToken(method.Parameters, includeServices: false);
        var paramIdentifiers = GetParameterIdentifiersWithCancellationToken(method.Parameters, includeServices: false);

        // Public method
        sb.AppendLine($"        public virtual {returnType} {method.UniqueName}({parameters})");
        sb.AppendLine("        {");

        var methodTarget = method.IsRemote ? $"{method.UniqueName}Property" : $"Local{method.UniqueName}";
        sb.AppendLine($"            return {methodTarget}({paramIdentifiers});");

        sb.AppendLine("        }");
        sb.AppendLine();

        // Remote method (if remote)
        if (method.IsRemote)
        {
            RenderCanRemoteMethod(sb, method);
        }

        // Local method (in Full mode, or for non-remote methods)
        if (mode == FactoryMode.Full || !method.IsRemote)
        {
            RenderCanLocalMethod(sb, method, model);
        }
    }

    private static void RenderCanRemoteMethod(StringBuilder sb, CanMethodModel method)
    {
        var returnType = method.IsTask ? "Task<Authorized>" : "Authorized";
        // Remote method signature excludes services
        var parameters = GetParameterDeclarationsWithOptionalCancellationToken(method.Parameters, includeServices: false);

        // Exclude CancellationToken from serialized parameters
        var serializedParams = string.Join(", ", method.Parameters
            .Where(p => !p.IsService && !p.IsCancellationToken)
            .Select(p => p.Name));

        sb.AppendLine($"        public virtual async {returnType} Remote{method.UniqueName}({parameters})");
        sb.AppendLine("        {");
        sb.AppendLine($"            return (await MakeRemoteDelegateRequest!.ForDelegate<Authorized>(typeof({method.UniqueName}Delegate), [{serializedParams}], cancellationToken))!;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void RenderCanLocalMethod(StringBuilder sb, CanMethodModel method, ClassFactoryModel model)
    {
        var asyncKeyword = method.IsAsync ? "async" : "";
        var returnType = method.IsTask ? "Task<Authorized>" : "Authorized";
        // Local method signature excludes services - they're obtained via ServiceProvider inside
        var parameters = GetParameterDeclarationsWithOptionalCancellationToken(method.Parameters, includeServices: false);

        sb.AppendLine($"        public {asyncKeyword} {returnType} Local{method.UniqueName}({parameters})");
        sb.AppendLine("        {");

        // Feature switch guard -- only emit for internal or [Remote] methods.
        // Public non-[Remote] methods run on both client and server.
        if (method.IsInternal || method.IsRemote)
        {
            sb.AppendLine("            if (!NeatooRuntime.IsServerRuntime)");
            sb.AppendLine("                throw new InvalidOperationException(\"Server-only method called in non-server runtime.\");");
            sb.AppendLine();
        }

        // Authorization checks (inside guard -- auth types are server-only)
        RenderAuthorizationChecks(sb, method);

        // Return success
        var returnText = "new Authorized(true)";
        if (method.IsTask && !method.IsAsync)
        {
            returnText = $"Task.FromResult({returnText})";
        }

        sb.AppendLine($"            return {returnText};");

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    #endregion

    #region Authorization Rendering

    private static void RenderAuthorizationChecks(StringBuilder sb, FactoryMethodModel method)
    {
        if (!method.HasAuth || method.Authorization == null)
        {
            return;
        }

        sb.AppendLine("            Authorized authorized;");

        // Group auth methods by class
        var authMethodsByClass = method.Authorization.AuthMethods.GroupBy(m => m.ClassName);
        foreach (var authClass in authMethodsByClass)
        {
            var className = authClass.Key;
            var varName = className.ToLower();

            sb.AppendLine($"            {className} {varName} = ServiceProvider.GetRequiredService<{className}>();");

            foreach (var authMethod in authClass)
            {
                RenderAuthMethodCall(sb, method, authMethod, varName);
            }
        }

        // ASP.NET Authorize checks
        if (method.Authorization.AspAuthorize.Count > 0)
        {
            sb.AppendLine("            var aspAuthorized = ServiceProvider.GetRequiredService<IAspAuthorize>();");

            var aspAuthDataList = method.Authorization.AspAuthorize.Select(asp =>
            {
                var ctorArgs = string.Join(", ", asp.ConstructorArgs);
                var namedArgs = string.Join(", ", asp.NamedArgs);
                var result = $"new AspAuthorizeData({ctorArgs})";
                if (!string.IsNullOrEmpty(namedArgs))
                {
                    result += $"{{ {namedArgs} }}";
                }
                return result;
            });

            var aspAuthDataText = string.Join(", ", aspAuthDataList);
            var aspForbid = method.Authorization.AspForbid.ToString().ToLower();
            sb.AppendLine($"            authorized = await aspAuthorized.Authorize([ {aspAuthDataText} ], {aspForbid});");

            if (!method.Authorization.AspForbid)
            {
                var returnType = GetReturnType(method, includeTask: false, includeAuth: true);
                sb.AppendLine("            if (!authorized.HasAccess)");
                sb.AppendLine("            {");
                sb.AppendLine($"                return new {returnType}(authorized);");
                sb.AppendLine("            }");
            }
        }
    }

    private static void RenderAuthMethodCall(StringBuilder sb, FactoryMethodModel factoryMethod, AuthMethodCall authMethod, string varName)
    {
        // Build parameter mapping from factory method params to auth method params
        var authParams = new List<string>();
        var factoryParams = factoryMethod.Parameters.Where(p => !p.IsTarget).ToList();

        foreach (var authParam in authMethod.Parameters)
        {
            var matchingFactoryParam = factoryParams.FirstOrDefault(p => p.Type == authParam.Type);
            if (matchingFactoryParam != null)
            {
                authParams.Add(matchingFactoryParam.Name);
                factoryParams.Remove(matchingFactoryParam);
            }
            else
            {
                authParams.Add($"/* Missing {authParam.Type} {authParam.Name} */");
            }
        }

        var paramText = string.Join(", ", authParams);
        var callText = $"{varName}.{authMethod.MethodName}({paramText})";

        if (authMethod.IsTask)
        {
            callText = $"await {callText}";
        }

        sb.AppendLine($"            authorized = {callText};");
        sb.AppendLine("            if (!authorized.HasAccess)");
        sb.AppendLine("            {");

        var aspForbid = factoryMethod.Authorization?.AspForbid ?? false;
        if (!aspForbid)
        {
            var isCanMethod = factoryMethod is CanMethodModel;
            var returnType = GetReturnType(factoryMethod, includeTask: false, includeAuth: true);

            string returnText;
            if (isCanMethod)
            {
                returnText = "authorized";
            }
            else
            {
                returnText = $"new {returnType}(authorized)";
            }

            if (!authMethod.IsTask && factoryMethod.IsTask && !factoryMethod.IsAsync)
            {
                returnText = $"Task.FromResult({returnText})";
            }

            sb.AppendLine($"                return {returnText};");
        }
        else
        {
            sb.AppendLine("                throw new NotAuthorizedException(authorized);");
        }

        sb.AppendLine("            }");
    }

    #endregion

    #region Service Registration Rendering

    private static void RenderFactoryServiceRegistrar(StringBuilder sb, ClassFactoryModel model, FactoryMode mode)
    {
        sb.AppendLine("        public static void FactoryServiceRegistrar(IServiceCollection services, NeatooFactory remoteLocal)");
        sb.AppendLine("        {");
        sb.AppendLine($"            services.AddScoped<{model.ImplementationTypeName}Factory>();");
        sb.AppendLine($"            services.AddScoped<I{model.ImplementationTypeName}Factory, {model.ImplementationTypeName}Factory>();");

        // Entity registration (only in Full mode)
        if (mode == FactoryMode.Full && model.RequiresEntityRegistration)
        {
            sb.AppendLine($"            services.AddTransient<{model.ImplementationTypeName}>();");
            if (model.ServiceTypeName != model.ImplementationTypeName)
            {
                sb.AppendLine($"            services.AddTransient<{model.ServiceTypeName}, {model.ImplementationTypeName}>();");
            }
        }

        // IFactorySave registration (only in Full mode)
        if (mode == FactoryMode.Full && model.HasDefaultSave)
        {
            sb.AppendLine($"            services.AddScoped<IFactorySave<{model.ImplementationTypeName}>, {model.ImplementationTypeName}Factory>();");
        }

        // Auth type registrations (preserves types from IL trimming)
        var authTypes = model.Methods
            .Where(m => m.HasAuth && m.Authorization != null)
            .SelectMany(m => m.Authorization!.AuthMethods)
            .Select(am => new { am.ClassName, am.ConcreteClassName })
            .GroupBy(a => a.ClassName)
            .Select(g => g.First())
            .ToList();

        if (authTypes.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("            // Explicit auth type registrations (IL trimming support)");
            foreach (var authType in authTypes)
            {
                if (authType.ConcreteClassName != null)
                {
                    // Interface with known concrete implementation
                    sb.AppendLine($"            services.TryAddTransient<{authType.ClassName}, {authType.ConcreteClassName}>();");
                }
                else
                {
                    // Concrete class used directly
                    sb.AppendLine($"            services.TryAddTransient<{authType.ClassName}>();");
                }
            }
        }

        // Ordinal converter registration
        if (model.RegisterOrdinalConverter)
        {
            sb.AppendLine();
            sb.AppendLine("            // Register trimming-compatible ordinal converter");
            sb.AppendLine($"            global::Neatoo.RemoteFactory.Internal.NeatooOrdinalConverterFactory.RegisterConverter(");
            sb.AppendLine($"                {model.ImplementationTypeName}.CreateOrdinalConverter());");
        }

        // Delegate service registrations (only in Full mode)
        if (mode == FactoryMode.Full)
        {
            foreach (var method in model.Methods.Where(m => m.IsRemote && !(m is WriteMethodModel)))
            {
                // Delegate registration excludes services - matches the delegate signature
                var parameters = GetParameterDeclarationsWithOptionalCancellationToken(method.Parameters, includeServices: false);
                var paramIdentifiers = GetParameterIdentifiersWithCancellationToken(method.Parameters, includeServices: false);

                sb.AppendLine($"            services.AddScoped<{method.UniqueName}Delegate>(cc => {{");
                sb.AppendLine($"                var factory = cc.GetRequiredService<{model.ImplementationTypeName}Factory>();");
                sb.AppendLine($"                return ({parameters}) => factory.Local{method.UniqueName}({paramIdentifiers});");
                sb.AppendLine("            });");
            }
        }

        // Event registrations
        sb.AppendLine();
        sb.AppendLine("            // Event registrations");
        sb.AppendLine("            if(remoteLocal == NeatooFactory.Remote)");
        sb.AppendLine("            {");

        foreach (var evt in model.Events)
        {
            RenderRemoteEventRegistration(sb, evt, model);
        }

        sb.AppendLine("            }");
        sb.AppendLine("            if(remoteLocal == NeatooFactory.Logical || remoteLocal == NeatooFactory.Server)");
        sb.AppendLine("            {");

        foreach (var evt in model.Events)
        {
            RenderLocalEventRegistration(sb, evt, model);
        }

        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    private static void RenderLocalEventRegistration(StringBuilder sb, EventMethodModel evt, ClassFactoryModel model)
    {
        var paramDecl = string.Join(", ", evt.Parameters
            .Where(p => !p.IsCancellationToken)
            .Select(p => $"{p.Type} {p.Name}"));

        var allParamIdentifiers = BuildEventMethodInvocationParams(evt);

        var serviceAssignments = string.Join("\n                            ",
            evt.ServiceParameters.Select(p => $"var {p.Name} = scope.ServiceProvider.GetRequiredService<{p.Type}>();"));

        var methodInvocation = evt.IsAsync
            ? $"await handler.{evt.Name}({allParamIdentifiers});"
            : $"handler.{evt.Name}({allParamIdentifiers});";

        sb.AppendLine($"                services.AddScoped<{model.ImplementationTypeName}.{evt.DelegateName}>(sp =>");
        sb.AppendLine("                {");
        sb.AppendLine("                    var scopeFactory = sp.GetRequiredService<IServiceScopeFactory>();");
        sb.AppendLine("                    var tracker = sp.GetRequiredService<IEventTracker>();");
        sb.AppendLine("                    var lifetime = sp.GetRequiredService<IHostApplicationLifetime>();");
        // Capture correlation context from parent scope
        sb.AppendLine("                    var parentCorrelation = sp.GetService<ICorrelationContext>();");
        sb.AppendLine($"                    return ({paramDecl}) =>");
        sb.AppendLine("                    {");
        // Capture correlation ID before Task.Run (outside the lambda closure)
        sb.AppendLine("                        var capturedCorrelationId = parentCorrelation?.CorrelationId;");
        sb.AppendLine("                        var task = Task.Run(async () =>");
        sb.AppendLine("                        {");
        sb.AppendLine("                            using var scope = scopeFactory.CreateScope();");
        // Set correlation ID in the new scope BEFORE resolving any services
        sb.AppendLine("                            var eventCorrelation = scope.ServiceProvider.GetService<ICorrelationContext>();");
        sb.AppendLine("                            if (eventCorrelation != null && capturedCorrelationId != null)");
        sb.AppendLine("                            {");
        sb.AppendLine("                                eventCorrelation.CorrelationId = capturedCorrelationId;");
        sb.AppendLine("                            }");
        sb.AppendLine("                            var ct = lifetime.ApplicationStopping;");
        sb.AppendLine($"                            var handler = scope.ServiceProvider.GetRequiredService<{model.ImplementationTypeName}>();");

        if (!string.IsNullOrEmpty(serviceAssignments))
        {
            sb.AppendLine($"                            {serviceAssignments}");
        }

        sb.AppendLine($"                            {methodInvocation}");
        sb.AppendLine("                        });");
        sb.AppendLine("                        tracker.Track(task);");
        sb.AppendLine("                        return task;");
        sb.AppendLine("                    };");
        sb.AppendLine("                });");
    }

    private static void RenderRemoteEventRegistration(StringBuilder sb, EventMethodModel evt, ClassFactoryModel model)
    {
        var paramDecl = string.Join(", ", evt.Parameters
            .Where(p => !p.IsCancellationToken)
            .Select(p => $"{p.Type} {p.Name}"));

        var serializedParams = string.Join(", ", evt.Parameters
            .Where(p => !p.IsService && !p.IsCancellationToken)
            .Select(p => p.Name));

        sb.AppendLine($"                services.AddTransient<{model.ImplementationTypeName}.{evt.DelegateName}>(cc =>");
        sb.AppendLine("                {");
        sb.AppendLine($"                    return ({paramDecl}) => cc.GetRequiredService<IMakeRemoteDelegateRequest>().ForDelegateEvent(typeof({model.ImplementationTypeName}.{evt.DelegateName}), [{serializedParams}]);");
        sb.AppendLine("                });");
    }

    #endregion

    #region Service Assignment Rendering

    private static void RenderServiceAssignments(StringBuilder sb, IReadOnlyList<ParameterModel> parameters)
    {
        foreach (var param in parameters.Where(p => p.IsService))
        {
            sb.AppendLine($"            var {param.Name} = ServiceProvider.GetRequiredService<{param.Type}>();");
        }
    }

    #endregion

    #region Helper Methods

    private static string GetReturnType(FactoryMethodModel method, bool includeTask, bool includeAuth)
    {
        var returnType = method.ServiceType;

        if (method is CanMethodModel)
        {
            returnType = "Authorized";
        }
        else if (method.HasAuth && includeAuth)
        {
            returnType = $"Authorized<{returnType}>";
        }
        else if (method.IsNullable)
        {
            returnType = $"{returnType}?";
        }

        if (includeTask && method.IsTask)
        {
            returnType = $"Task<{returnType}>";
        }

        return returnType;
    }

    private static string GetParameterDeclarationsWithOptionalCancellationToken(IReadOnlyList<ParameterModel> parameters, bool includeServices = true, bool includeTarget = true)
    {
        var paramsWithoutCt = parameters
            .Where(p => (includeServices || !p.IsService) && (includeTarget || !p.IsTarget) && !p.IsCancellationToken)
            .ToList();

        var hasParamsParameter = paramsWithoutCt.Any(p => p.IsParams);

        if (hasParamsParameter)
        {
            var regularParams = paramsWithoutCt.Where(p => !p.IsParams).Select(p => $"{p.Type} {p.Name}").ToList();
            var paramsParam = paramsWithoutCt.First(p => p.IsParams);

            regularParams.Add("CancellationToken cancellationToken = default");
            regularParams.Add($"params {paramsParam.Type} {paramsParam.Name}");

            return string.Join(", ", regularParams);
        }
        else
        {
            var paramsList = paramsWithoutCt.Select(p => $"{p.Type} {p.Name}").ToList();
            paramsList.Add("CancellationToken cancellationToken = default");
            return string.Join(", ", paramsList);
        }
    }

    private static string GetParameterIdentifiersWithCancellationToken(IReadOnlyList<ParameterModel> parameters, bool includeServices = true, bool includeTarget = true)
    {
        var paramsWithoutCt = parameters
            .Where(p => (includeServices || !p.IsService) && (includeTarget || !p.IsTarget) && !p.IsCancellationToken)
            .ToList();

        var hasParamsParameter = paramsWithoutCt.Any(p => p.IsParams);

        if (hasParamsParameter)
        {
            var regularParams = paramsWithoutCt.Where(p => !p.IsParams).Select(p => p.Name).ToList();
            var paramsParam = paramsWithoutCt.First(p => p.IsParams);

            regularParams.Add("cancellationToken");
            regularParams.Add(paramsParam.Name);

            return string.Join(", ", regularParams);
        }
        else
        {
            var identifiersList = paramsWithoutCt.Select(p => p.Name).ToList();
            identifiersList.Add("cancellationToken");
            return string.Join(", ", identifiersList);
        }
    }

    private static string GetParameterIdentifiersForDomainInvocation(IReadOnlyList<ParameterModel> parameters)
    {
        // Include services, exclude target, pass cancellationToken if present
        return string.Join(", ", parameters
            .Where(p => !p.IsTarget)
            .Select(p => p.IsCancellationToken ? "cancellationToken" : p.Name));
    }

    private static string BuildEventMethodInvocationParams(EventMethodModel evt)
    {
        // Build the full parameter list including services
        var allParams = new List<string>();

        // Add data parameters (exclude CancellationToken - it's handled separately as 'ct')
        allParams.AddRange(evt.Parameters
            .Where(p => !p.IsCancellationToken)
            .Select(p => p.Name));

        // Add service parameters (resolved from DI)
        allParams.AddRange(evt.ServiceParameters.Select(p => p.Name));

        // Add ct if domain method has CancellationToken
        if (evt.Parameters.Any(p => p.IsCancellationToken))
        {
            allParams.Add("ct");
        }

        return string.Join(", ", allParams);
    }

    #endregion
}
