// src/Generator/Renderer/EventPreservationRenderer.cs
// Renders the per-assembly event-preservation registrar (TRIM-007): one generated
// static class per compilation that preserves every concrete FactoryEventBase
// descendant (and its nested DTO graph) from IL trimming. Discovered at runtime by
// the existing assembly-level [NeatooFactoryRegistrar] scan — the attribute's
// [DynamicallyAccessedMembers] on its Type parameter roots FactoryServiceRegistrar
// under TrimMode=full, whose body then roots the preservation call sites.

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Neatoo.RemoteFactory.Generator.Renderer;

internal static class EventPreservationRenderer
{
    /// <summary>
    /// Renders the registrar, or returns null when the compilation declares no
    /// (accessible, concrete) FactoryEventBase descendants. Buckets are merged
    /// across events, deduplicated, and ordinally sorted so the generated bytes
    /// are deterministic across builds.
    /// </summary>
    public static (string HintName, string Source)? Render(ImmutableArray<FactoryEventInfo?> events)
    {
        var items = events.Where(e => e != null).Select(e => e!).ToList();
        if (items.Count == 0)
        {
            return null;
        }

        var registerTypes = new SortedSet<string>(StringComparer.Ordinal);
        var preserveTypes = new SortedSet<string>(StringComparer.Ordinal);

        foreach (var item in items)
        {
            foreach (var t in item.RegisterTypes)
            {
                registerTypes.Add(t);
            }

            foreach (var t in item.PreserveTypes)
            {
                preserveTypes.Add(t);
            }
        }

        // A type never lands in both buckets within one walk, but distinct events
        // could theoretically disagree only if ctor shape differed — impossible for
        // the same FQN. Keep Register authoritative on any overlap.
        preserveTypes.ExceptWith(registerTypes);

        if (registerTypes.Count == 0 && preserveTypes.Count == 0)
        {
            return null;
        }

        var assemblyName = items[0].AssemblyName;
        var ns = SanitizeNamespace(assemblyName);

        var sb = new StringBuilder();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Neatoo.RemoteFactory;");
        sb.AppendLine("using Neatoo.RemoteFactory.Internal;");
        sb.AppendLine();
        sb.AppendLine($"[assembly: Neatoo.RemoteFactory.NeatooFactoryRegistrar(typeof(global::{ns}.NeatooEventPreservationRegistrar))]");
        sb.AppendLine();
        sb.AppendLine("/*");
        sb.AppendLine("    READONLY - DO NOT EDIT!!!!");
        sb.AppendLine("    Generated by Neatoo.RemoteFactory");
        sb.AppendLine("*/");
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Preserves FactoryEventBase descendants (and their nested DTO graphs) from");
        sb.AppendLine("    /// IL trimming. Invoked by the assembly-level NeatooFactoryRegistrar scan.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal static class NeatooEventPreservationRegistrar");
        sb.AppendLine("    {");
        sb.AppendLine("        internal static void FactoryServiceRegistrar(IServiceCollection services, NeatooFactory remoteLocal)");
        sb.AppendLine("        {");

        foreach (var t in registerTypes)
        {
            sb.AppendLine($"            DtoConstructorRegistry.Register<{t}>(() => new {t}());");
        }

        foreach (var t in preserveTypes)
        {
            sb.AppendLine($"            DtoConstructorRegistry.PreserveType<{t}>();");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return ($"{assemblyName}.NeatooEventPreservation.g.cs", sb.ToString());
    }

    /// <summary>
    /// Assembly names are usually valid dotted identifiers; sanitize each segment
    /// for the edge cases (hyphens, leading digits) so the namespace always compiles.
    /// </summary>
    private static string SanitizeNamespace(string assemblyName)
    {
        var segments = assemblyName.Split('.');
        for (var i = 0; i < segments.Length; i++)
        {
            var chars = segments[i].ToCharArray();
            for (var c = 0; c < chars.Length; c++)
            {
                if (!char.IsLetterOrDigit(chars[c]) && chars[c] != '_')
                {
                    chars[c] = '_';
                }
            }

            var segment = new string(chars);
            if (segment.Length == 0 || char.IsDigit(segment[0]))
            {
                segment = "_" + segment;
            }

            segments[i] = segment;
        }

        return string.Join(".", segments);
    }
}
