// src/Generator/Renderer/OrdinalRenderer.cs
// Renders ordinal serialization support code for entities.

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Neatoo.RemoteFactory.Generator.Model;

namespace Neatoo.RemoteFactory.Generator.Renderer;

/// <summary>
/// Renders ordinal serialization support code for entities.
/// This enables compact JSON serialization using arrays instead of objects with property names.
/// </summary>
internal static class OrdinalRenderer
{
    /// <summary>
    /// Computes the total number of ordinal array slots for the given properties.
    /// LazyLoad&lt;T&gt; properties occupy two slots (Value + IsLoaded); all others occupy one.
    /// </summary>
    private static int GetTotalSlotCount(IReadOnlyList<OrdinalPropertyModel> properties)
    {
        int count = 0;
        for (int i = 0; i < properties.Count; i++)
        {
            count += properties[i].IsLazyLoad ? 2 : 1;
        }
        return count;
    }

    /// <summary>
    /// Computes the slot index for a given property index.
    /// Each LazyLoad&lt;T&gt; property before this index adds an extra slot.
    /// </summary>
    private static int GetSlotIndex(IReadOnlyList<OrdinalPropertyModel> properties, int propertyIndex)
    {
        int slot = 0;
        for (int i = 0; i < propertyIndex; i++)
        {
            slot += properties[i].IsLazyLoad ? 2 : 1;
        }
        return slot;
    }

    /// <summary>
    /// Renders the ordinal serialization code for a type.
    /// </summary>
    public static string Render(OrdinalSerializationModel model)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Using statements
        foreach (var u in model.Usings)
        {
            sb.AppendLine(u);
        }

        sb.AppendLine();
        sb.AppendLine("/*");
        sb.AppendLine("    READONLY - DO NOT EDIT!!!!");
        sb.AppendLine("    Generated by Neatoo.RemoteFactory - Ordinal Serialization Support");
        sb.AppendLine("*/");

        sb.AppendLine($"namespace {model.Namespace}");
        sb.AppendLine("{");

        // Converter class
        RenderConverterClass(sb, model);

        // Partial class extension
        RenderPartialClass(sb, model);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void RenderConverterClass(StringBuilder sb, OrdinalSerializationModel model)
    {
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Strongly-typed ordinal converter for {model.TypeName}. No reflection required.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    internal sealed class {model.TypeName}OrdinalConverter : global::System.Text.Json.Serialization.JsonConverter<{model.FullTypeName}>");
        sb.AppendLine("    {");

        // Read method
        RenderReadMethod(sb, model);

        // Write method
        RenderWriteMethod(sb, model);

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void RenderReadMethod(StringBuilder sb, OrdinalSerializationModel model)
    {
        sb.AppendLine($"        public override {model.FullTypeName}? Read(");
        sb.AppendLine("            ref global::System.Text.Json.Utf8JsonReader reader,");
        sb.AppendLine("            global::System.Type typeToConvert,");
        sb.AppendLine("            global::System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine("        {");

        sb.AppendLine("            if (reader.TokenType == global::System.Text.Json.JsonTokenType.Null)");
        sb.AppendLine("                return null;");
        sb.AppendLine();

        sb.AppendLine("            if (reader.TokenType != global::System.Text.Json.JsonTokenType.StartArray)");
        sb.AppendLine($"                throw new global::System.Text.Json.JsonException(");
        sb.AppendLine($"                    $\"Expected StartArray for {model.TypeName} ordinal format, got {{reader.TokenType}}\");");
        sb.AppendLine();

        sb.AppendLine("            reader.Read(); // Move past StartArray");
        sb.AppendLine();

        // Read each property using trim-safe Deserialize overload with GetTypeInfo.
        // Cast to the correct type since the non-generic overload returns object?.
        // Non-nullable types get null-forgiving operator; nullable types allow null.
        // For nullable properties, check for null token first to avoid deserialization errors
        // when the JsonTypeInfo is for the non-nullable base type (e.g., int vs int?).
        // LazyLoad<T> properties occupy two consecutive slots: Value (inner type T) and IsLoaded (bool).
        var totalSlotCount = GetTotalSlotCount(model.Properties);
        int slotIndex = 0;
        for (int i = 0; i < model.Properties.Count; i++)
        {
            var prop = model.Properties[i];

            if (prop.IsLazyLoad)
            {
                // Two-slot LazyLoad<T> deserialization: read Value at slot N, IsLoaded at slot N+1
                var innerType = prop.InnerType!.TrimEnd();
                sb.AppendLine($"            // {prop.Name} (LazyLoad<{innerType}>) - slots {slotIndex} and {slotIndex + 1}");

                // Slot N: the inner value (always nullable since unloaded LazyLoad has null value)
                sb.AppendLine($"            {innerType}? prop{slotIndex} = reader.TokenType == global::System.Text.Json.JsonTokenType.Null");
                sb.AppendLine($"                ? default({innerType})");
                sb.AppendLine($"                : ({innerType})global::System.Text.Json.JsonSerializer.Deserialize(ref reader, options.GetTypeInfo(typeof({innerType})))!;");
                sb.AppendLine("            reader.Read();");

                // Slot N+1: isLoaded bool
                sb.AppendLine($"            var prop{slotIndex + 1} = (bool)global::System.Text.Json.JsonSerializer.Deserialize(ref reader, options.GetTypeInfo(typeof(bool)))!;");
                sb.AppendLine("            reader.Read();");

                // Construct the LazyLoad<T> from the two slots
                sb.AppendLine($"            var prop{i}_lazy = prop{slotIndex + 1}");
                sb.AppendLine($"                ? new global::Neatoo.RemoteFactory.LazyLoad<{innerType}>(prop{slotIndex})");
                sb.AppendLine($"                : new global::Neatoo.RemoteFactory.LazyLoad<{innerType}>();");

                slotIndex += 2;
            }
            else
            {
                var baseType = prop.Type.TrimEnd();
                var castType = prop.IsNullable ? $"{baseType}?" : baseType;
                var nullForgiving = prop.IsNullable ? "" : "!";
                sb.AppendLine($"            // {prop.Name} ({castType}) - position {slotIndex}");
                if (prop.IsNullable)
                {
                    sb.AppendLine($"            {castType} prop{slotIndex} = reader.TokenType == global::System.Text.Json.JsonTokenType.Null");
                    sb.AppendLine($"                ? default({castType})");
                    sb.AppendLine($"                : ({baseType})global::System.Text.Json.JsonSerializer.Deserialize(ref reader, options.GetTypeInfo(typeof({baseType})))!;");
                }
                else
                {
                    sb.AppendLine($"            var prop{slotIndex} = ({castType})global::System.Text.Json.JsonSerializer.Deserialize(ref reader, options.GetTypeInfo(typeof({baseType}))){nullForgiving};");
                }
                sb.AppendLine("            reader.Read();");

                slotIndex++;
            }
        }

        sb.AppendLine();
        sb.AppendLine("            if (reader.TokenType != global::System.Text.Json.JsonTokenType.EndArray)");
        sb.AppendLine($"                throw new global::System.Text.Json.JsonException(");
        sb.AppendLine($"                    $\"Too many values in ordinal array for {model.TypeName}. Expected {totalSlotCount}.\");");
        sb.AppendLine();

        // Construct the object
        RenderConstruction(sb, model, "prop");

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void RenderWriteMethod(StringBuilder sb, OrdinalSerializationModel model)
    {
        sb.AppendLine("        public override void Write(");
        sb.AppendLine("            global::System.Text.Json.Utf8JsonWriter writer,");
        sb.AppendLine($"            {model.FullTypeName} value,");
        sb.AppendLine("            global::System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine("        {");

        sb.AppendLine("            if (value == null)");
        sb.AppendLine("            {");
        sb.AppendLine("                writer.WriteNullValue();");
        sb.AppendLine("                return;");
        sb.AppendLine("            }");
        sb.AppendLine();

        sb.AppendLine("            writer.WriteStartArray();");

        // Write each property using trim-safe Serialize overload with GetTypeInfo.
        // For nullable properties, emit a null check and write null directly to avoid
        // unboxing failures when passing null to Serialize with a non-nullable JsonTypeInfo.
        // LazyLoad<T> properties write two consecutive slots: Value (inner type T) and IsLoaded (bool).
        for (int i = 0; i < model.Properties.Count; i++)
        {
            var prop = model.Properties[i];

            if (prop.IsLazyLoad)
            {
                // Two-slot LazyLoad<T> serialization: write Value at slot N, IsLoaded at slot N+1
                var innerType = prop.InnerType!.TrimEnd();
                // Value is always nullable (unloaded LazyLoad has null value)
                sb.AppendLine($"            if (value.{prop.Name} is not null && value.{prop.Name}.Value is not null)");
                sb.AppendLine($"                global::System.Text.Json.JsonSerializer.Serialize(writer, value.{prop.Name}.Value, options.GetTypeInfo(typeof({innerType})));");
                sb.AppendLine($"            else");
                sb.AppendLine($"                writer.WriteNullValue();");
                // IsLoaded
                sb.AppendLine($"            global::System.Text.Json.JsonSerializer.Serialize(writer, value.{prop.Name}?.IsLoaded ?? false, options.GetTypeInfo(typeof(bool)));");
            }
            else
            {
                var baseType = prop.Type.TrimEnd();
                if (prop.IsNullable)
                {
                    sb.AppendLine($"            if (value.{prop.Name} is not null)");
                    sb.AppendLine($"                global::System.Text.Json.JsonSerializer.Serialize(writer, value.{prop.Name}, options.GetTypeInfo(typeof({baseType})));");
                    sb.AppendLine($"            else");
                    sb.AppendLine($"                writer.WriteNullValue();");
                }
                else
                {
                    sb.AppendLine($"            global::System.Text.Json.JsonSerializer.Serialize(writer, value.{prop.Name}, options.GetTypeInfo(typeof({baseType})));");
                }
            }
        }

        sb.AppendLine("            writer.WriteEndArray();");
        sb.AppendLine("        }");
    }

    private static void RenderPartialClass(StringBuilder sb, OrdinalSerializationModel model)
    {
        var recordKeyword = model.IsRecord ? "record" : "class";

        sb.AppendLine($"    partial {recordKeyword} {model.TypeName} : global::Neatoo.RemoteFactory.IOrdinalSerializable, global::Neatoo.RemoteFactory.IOrdinalSerializationMetadata, global::Neatoo.RemoteFactory.IOrdinalConverterProvider<{model.FullTypeName}>");
        sb.AppendLine("    {");

        // PropertyNames static property
        // LazyLoad<T> properties emit two entries: "Name" and "Name__IsLoaded"
        var propertyNameEntries = new List<string>();
        foreach (var p in model.Properties)
        {
            if (p.IsLazyLoad)
            {
                propertyNameEntries.Add($"\"{p.Name}\"");
                propertyNameEntries.Add($"\"{p.Name}__IsLoaded\"");
            }
            else
            {
                propertyNameEntries.Add($"\"{p.Name}\"");
            }
        }
        var propertyNamesArray = string.Join(", ", propertyNameEntries);
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Property names in ordinal order (alphabetical, base properties first).");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static string[] PropertyNames {{ get; }} = new[] {{ {propertyNamesArray} }};");
        sb.AppendLine();

        // PropertyTypes static property
        // Note: Nullable annotations are already stripped at the source (FactoryGenerator.Types.cs)
        // using WithNullableAnnotation(NullableAnnotation.NotAnnotated) to avoid CS8639 errors.
        // LazyLoad<T> properties emit two entries: typeof(InnerType) and typeof(bool)
        var propertyTypeEntries = new List<string>();
        foreach (var p in model.Properties)
        {
            if (p.IsLazyLoad)
            {
                propertyTypeEntries.Add($"typeof({p.InnerType})");
                propertyTypeEntries.Add("typeof(bool)");
            }
            else
            {
                propertyTypeEntries.Add($"typeof({p.Type})");
            }
        }
        var propertyTypesArray = string.Join(", ", propertyTypeEntries);
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Property types in ordinal order.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static Type[] PropertyTypes {{ get; }} = new[] {{ {propertyTypesArray} }};");
        sb.AppendLine();

        // ToOrdinalArray method
        // LazyLoad<T> properties emit two values: .Value and .IsLoaded
        var toArrayEntries = new List<string>();
        foreach (var p in model.Properties)
        {
            if (p.IsLazyLoad)
            {
                toArrayEntries.Add($"this.{p.Name}?.Value");
                toArrayEntries.Add($"this.{p.Name}?.IsLoaded ?? false");
            }
            else
            {
                toArrayEntries.Add($"this.{p.Name}");
            }
        }
        var toArrayValues = string.Join(", ", toArrayEntries);
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Converts this instance to an ordinal array for compact JSON serialization.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public object?[] ToOrdinalArray()");
        sb.AppendLine("        {");
        sb.AppendLine($"            return new object?[] {{ {toArrayValues} }};");
        sb.AppendLine("        }");
        sb.AppendLine();

        // FromOrdinalArray static method
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Creates an instance from an ordinal array.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static object FromOrdinalArray(object?[] values)");
        sb.AppendLine("        {");
        RenderFromOrdinalArrayConstruction(sb, model);
        sb.AppendLine("        }");
        sb.AppendLine();

        // CreateOrdinalConverter static method
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Creates a trimming-compatible ordinal converter for this type.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static global::System.Text.Json.Serialization.JsonConverter<{model.FullTypeName}> CreateOrdinalConverter()");
        sb.AppendLine($"            => new {model.TypeName}OrdinalConverter();");

        sb.AppendLine("    }");
    }

    private static void RenderConstruction(StringBuilder sb, OrdinalSerializationModel model, string propPrefix)
    {
        if (model.IsRecord && model.HasPrimaryConstructor && model.ConstructorParameterNames.Count > 0)
        {
            // For records with primary constructors, use constructor syntax
            var constructorArgs = BuildConstructorArgs(model, propPrefix);
            sb.AppendLine($"            return new {model.FullTypeName}({constructorArgs});");
        }
        else
        {
            // For classes and records without primary constructors, use object initializer.
            // LazyLoad<T> properties use the pre-constructed lazy variable (prop{i}_lazy)
            // instead of the raw slot variable, because their value was assembled from two slots.
            sb.AppendLine($"            return new {model.FullTypeName}");
            sb.AppendLine("            {");

            int slotIndex = 0;
            for (int i = 0; i < model.Properties.Count; i++)
            {
                var prop = model.Properties[i];
                var comma = i < model.Properties.Count - 1 ? "," : "";

                if (prop.IsLazyLoad)
                {
                    // Use the pre-constructed LazyLoad variable from RenderReadMethod
                    sb.AppendLine($"                {prop.Name} = {propPrefix}{i}_lazy{comma}");
                    slotIndex += 2;
                }
                else
                {
                    var isEffectivelyNullable = prop.IsNullable || prop.Type.EndsWith("?");
                    var nullForgiving = isEffectivelyNullable ? "" : "!";
                    sb.AppendLine($"                {prop.Name} = {propPrefix}{slotIndex}{nullForgiving}{comma}");
                    slotIndex++;
                }
            }

            sb.AppendLine("            };");
        }
    }

    private static void RenderFromOrdinalArrayConstruction(StringBuilder sb, OrdinalSerializationModel model)
    {
        if (model.IsRecord && model.HasPrimaryConstructor && model.ConstructorParameterNames.Count > 0)
        {
            // For records with primary constructors, use constructor syntax
            var constructorArgs = BuildConstructorArgsForFromArray(model);
            sb.AppendLine($"            return new {model.TypeName}({constructorArgs});");
        }
        else
        {
            // For classes and records without primary constructors, use object initializer.
            // LazyLoad<T> properties occupy two consecutive array slots: Value and IsLoaded.
            sb.AppendLine($"            return new {model.TypeName}");
            sb.AppendLine("            {");

            int slotIndex = 0;
            for (int i = 0; i < model.Properties.Count; i++)
            {
                var prop = model.Properties[i];
                var comma = i < model.Properties.Count - 1 ? "," : "";

                if (prop.IsLazyLoad)
                {
                    // Reconstruct LazyLoad<T> from two array slots: [value, isLoaded]
                    var innerType = prop.InnerType!.TrimEnd();
                    sb.AppendLine($"                {prop.Name} = (bool)values[{slotIndex + 1}]!"); // isLoaded check
                    sb.AppendLine($"                    ? new global::Neatoo.RemoteFactory.LazyLoad<{innerType}>(({innerType}?)values[{slotIndex}])");
                    sb.AppendLine($"                    : new global::Neatoo.RemoteFactory.LazyLoad<{innerType}>(){comma}");
                    slotIndex += 2;
                }
                else
                {
                    // For nullable types, add ? to the cast type to avoid CS8600
                    // when casting from object? to a non-nullable type.
                    var baseType = prop.Type.TrimEnd();
                    var needsNullableSuffix = prop.IsNullable && !baseType.EndsWith("?");
                    var castType = needsNullableSuffix ? $"{baseType}?" : baseType;
                    var cast = $"({castType})";
                    var nullForgiving = prop.IsNullable ? "" : "!";
                    sb.AppendLine($"                {prop.Name} = {cast}values[{slotIndex}]{nullForgiving}{comma}");
                    slotIndex++;
                }
            }

            sb.AppendLine("            };");
        }
    }

    private static string BuildConstructorArgs(OrdinalSerializationModel model, string propPrefix)
    {
        var args = new List<string>();

        // Build a mapping from property name to its index
        var propertyToIndex = new Dictionary<string, int>();
        for (int i = 0; i < model.Properties.Count; i++)
        {
            propertyToIndex[model.Properties[i].Name] = i;
        }

        // Arguments must be in constructor parameter order
        foreach (var paramName in model.ConstructorParameterNames)
        {
            if (propertyToIndex.TryGetValue(paramName, out var idx))
            {
                var prop = model.Properties[idx];
                var isEffectivelyNullable = prop.IsNullable || prop.Type.EndsWith("?");
                var nullForgiving = isEffectivelyNullable ? "" : "!";
                args.Add($"{propPrefix}{idx}{nullForgiving}");
            }
        }

        return string.Join(", ", args);
    }

    private static string BuildConstructorArgsForFromArray(OrdinalSerializationModel model)
    {
        var args = new List<string>();

        // Build a mapping from property name to its index
        var propertyToIndex = new Dictionary<string, int>();
        for (int i = 0; i < model.Properties.Count; i++)
        {
            propertyToIndex[model.Properties[i].Name] = i;
        }

        // Arguments must be in constructor parameter order
        foreach (var paramName in model.ConstructorParameterNames)
        {
            if (propertyToIndex.TryGetValue(paramName, out var idx))
            {
                var prop = model.Properties[idx];
                // For nullable types, add ? to the cast type to avoid CS8600
                // when casting from object? to a non-nullable type.
                // TrimEnd ensures no trailing whitespace in the type string.
                // Defensive: only add ? if type doesn't already end with ? (shouldn't happen after source fix).
                var baseType = prop.Type.TrimEnd();
                var needsNullableSuffix = prop.IsNullable && !baseType.EndsWith("?");
                var castType = needsNullableSuffix ? $"{baseType}?" : baseType;
                var cast = $"({castType.TrimEnd()})";  // Extra TrimEnd for safety
                var nullForgiving = prop.IsNullable ? "" : "!";
                args.Add($"{cast}values[{idx}]{nullForgiving}");
            }
        }

        return string.Join(", ", args);
    }
}
