#nullable enable

using System.Linq;
using System.Text;
using Neatoo.RemoteFactory.Generator.Model;

namespace Neatoo.RemoteFactory.Generator.Renderer;

/// <summary>
/// Renders code for [FactoryEventHandler&lt;T&gt;] classes.
/// Static methods → server-side FactoryEventHandlerRegistry registration.
/// Instance methods → client-side FactoryEventRelayRegistry registration.
/// </summary>
internal static class RelayHandlerRenderer
{
    public static string Render(RelayHandlerModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        foreach (var u in model.Usings)
        {
            sb.AppendLine(u);
        }

        sb.AppendLine();

        // Assembly-level attribute for trimming-safe factory discovery
        sb.AppendLine($"[assembly: Neatoo.RemoteFactory.NeatooFactoryRegistrar(typeof({model.Namespace}.{model.ClassName}))]");
        sb.AppendLine();

        sb.AppendLine("/*");
        sb.AppendLine("    READONLY - DO NOT EDIT!!!!");
        sb.AppendLine("    Generated by Neatoo.RemoteFactory");
        sb.AppendLine("*/");

        sb.AppendLine($"namespace {model.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    {model.ClassSignatureText} {{");
        sb.AppendLine();

        // FactoryServiceRegistrar method
        sb.AppendLine("        internal static void FactoryServiceRegistrar(IServiceCollection services, NeatooFactory remoteLocal)");
        sb.AppendLine("        {");

        foreach (var entry in model.Entries)
        {
            if (entry.IsStatic)
            {
                RenderServerSideHandler(sb, entry, model.ClassName);
            }
            else
            {
                RenderClientSideRelayHandler(sb, entry, model.ClassName);
            }
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Server-side: register into FactoryEventHandlerRegistry with isolated scope, [Service] injection, CT.
    /// </summary>
    private static void RenderServerSideHandler(StringBuilder sb, EventHandlerEntry handler, string className)
    {
        var eventTypeName = handler.EventTypeName;

        var allParamIdentifiers = string.Join(", ",
            handler.Parameters.Where(p => !p.IsCancellationToken)
                .Select(p => p.Name)
            .Concat(handler.ServiceParameters.Select(p => p.Name))
            .Concat(handler.Parameters.Where(p => p.IsCancellationToken).Select(_ => "ct")));

        var serviceAssignments = string.Join("\n                            ",
            handler.ServiceParameters.Select(p => $"var {p.Name} = scope.ServiceProvider.GetRequiredService<{p.Type}>();"));

        var methodInvocation = handler.IsAsync
            ? $"await {className}.{handler.MethodName}({allParamIdentifiers});"
            : $"{className}.{handler.MethodName}({allParamIdentifiers});";

        sb.AppendLine("            if (NeatooRuntime.IsServerRuntime)");
        sb.AppendLine("            {");
        sb.AppendLine($"                FactoryEventHandlerRegistry.RegisterHandler<{eventTypeName}>((sp, eventObj, options) =>");
        sb.AppendLine("                {");
        sb.AppendLine("                    var scopeFactory = sp.GetRequiredService<IServiceScopeFactory>();");
        sb.AppendLine("                    var tracker = sp.GetRequiredService<IEventTracker>();");
        sb.AppendLine("                    var lifetime = sp.GetRequiredService<IHostApplicationLifetime>();");
        sb.AppendLine("                    var parentCorrelation = sp.GetService<ICorrelationContext>();");
        sb.AppendLine("                    var capturedCorrelationId = parentCorrelation?.CorrelationId;");
        sb.AppendLine($"                    var {handler.Parameters.First(p => !p.IsCancellationToken).Name} = ({eventTypeName})eventObj;");
        sb.AppendLine("                    var task = Task.Run(async () =>");
        sb.AppendLine("                    {");
        sb.AppendLine("                        using var scope = scopeFactory.CreateScope();");
        sb.AppendLine("                        var eventCorrelation = scope.ServiceProvider.GetService<ICorrelationContext>();");
        sb.AppendLine("                        if (eventCorrelation != null && capturedCorrelationId != null)");
        sb.AppendLine("                        {");
        sb.AppendLine("                            eventCorrelation.CorrelationId = capturedCorrelationId;");
        sb.AppendLine("                        }");
        if (handler.Parameters.Any(p => p.IsCancellationToken))
        {
            sb.AppendLine("                        var ct = lifetime.ApplicationStopping;");
        }
        if (!string.IsNullOrEmpty(serviceAssignments))
        {
            sb.AppendLine($"                        {serviceAssignments}");
        }
        sb.AppendLine($"                        {methodInvocation}");
        sb.AppendLine("                    });");
        sb.AppendLine("                    tracker.Track(task);");
        sb.AppendLine("                    return task;");
        sb.AppendLine("                });");
        sb.AppendLine("            }");
    }

    /// <summary>
    /// Client-side: register handler type with dispatch delegate and deserializer into FactoryEventRelayRegistry.
    /// </summary>
    private static void RenderClientSideRelayHandler(StringBuilder sb, EventHandlerEntry handler, string className)
    {
        var eventTypeName = handler.EventTypeName;

        sb.AppendLine($"            FactoryEventRelayRegistry.RegisterHandlerType(");
        sb.AppendLine($"                typeof({className}),");
        sb.AppendLine($"                typeof({eventTypeName}).FullName!,");
        sb.AppendLine($"                (h, evt) => (({className})h).{handler.MethodName}(({eventTypeName})evt),");
        sb.AppendLine($"                (json, serializer) => serializer.Deserialize<{eventTypeName}>(json)!);");
    }
}
