#nullable enable

using System.Globalization;
using System.Linq;
using System.Text;
using Neatoo.RemoteFactory.Generator.Model;

namespace Neatoo.RemoteFactory.Generator.Renderer;

/// <summary>
/// Renders server-side FactoryEventHandlerRegistry registrations for
/// [FactoryEventHandler&lt;T&gt;] classes with static handler methods. Client-side relay
/// emission and event-type trimming preservation have been removed — event preservation
/// is provided by <c>[DynamicallyAccessedMembers]</c> on <c>FactoryEventBase</c>.
/// </summary>
internal static class RelayHandlerRenderer
{
    public static string Render(RelayHandlerModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        foreach (var u in model.Usings)
        {
            sb.AppendLine(u);
        }

        sb.AppendLine();

        // Assembly-level attribute for trimming-safe factory discovery.
        // Targets the generated registrar holder, NEVER the user's own class: the
        // attribute's [DynamicallyAccessedMembers] preserves every method on whatever
        // type it names, bodies included, so naming the user's class would ship their
        // handler bodies — and the server-only services those bodies reach — to a
        // trimmed client (TRIM-008).
        //
        // global:: added here at the same time. Its absence was a latent bug: a
        // consumer namespace that shadows the first segment of this one would bind
        // the attribute argument to the wrong type.
        sb.AppendLine($"[assembly: Neatoo.RemoteFactory.NeatooFactoryRegistrar(typeof(global::{model.Namespace}.{RegistrarHolderPrefix}{model.ClassName}))]");
        sb.AppendLine();

        sb.AppendLine("/*");
        sb.AppendLine("    READONLY - DO NOT EDIT!!!!");
        sb.AppendLine("    Generated by Neatoo.RemoteFactory");
        sb.AppendLine("*/");

        sb.AppendLine($"namespace {model.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    {model.ClassSignatureText} {{");
        sb.AppendLine();

        sb.AppendLine("        internal static void FactoryServiceRegistrar(IServiceCollection services, NeatooFactory remoteLocal)");
        sb.AppendLine("        {");

        foreach (var entry in model.Entries)
        {
            // Every entry is a static handler — the transform silently filters instance methods.
            RenderServerSideHandler(sb, entry, model.ClassName);
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");

        // Registrar holder — the assembly attribute's DAM target. Exists so the DAM
        // blast radius is this one forwarding method instead of every method on the
        // user's handler class. Top-level rather than nested, matching the proven
        // in-tree shape (EventPreservationRenderer) and StaticFactoryRenderer's holder.
        sb.AppendLine();
        RenderRegistrarHolder(sb, model);
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Prefix for the generated relay-handler registrar holder type.
    /// </summary>
    /// <remarks>
    /// Deliberately a PREFIX, for the same reason as
    /// <see cref="StaticFactoryRenderer.RegistrarHolderPrefix"/>: a suffixed name leaves
    /// <c>global::Ns.MyHandlers</c> a substring of the holder's own fully-qualified name,
    /// which turns the "attribute must not name the consumer's type" regression assertion
    /// into a false red and an unclosed <c>Contains</c> into a false green.
    /// <para>
    /// Deliberately DISTINCT from the static-factory prefix. A class carrying both
    /// <c>[Factory]</c> and <c>[FactoryEventHandler&lt;T&gt;]</c> already emits duplicate
    /// <c>FactoryServiceRegistrar</c> members (CS0111 — Deferred Work item 15, broken at
    /// HEAD). A shared holder prefix would stack a CS0101 duplicate-type error on top,
    /// changing that shape's failure signature for the worse.
    /// </para>
    /// </remarks>
    internal const string RegistrarHolderPrefix = "NeatooEventHandlerRegistrar_";

    /// <summary>
    /// Emits the holder the assembly attribute points at. It does nothing but forward
    /// to the real registrar on the user's partial class — the indirection exists purely
    /// so the attribute's [DynamicallyAccessedMembers] has a single-method type to
    /// preserve instead of the user's whole handler class.
    /// </summary>
    /// <remarks>
    /// Forwarding rather than hosting: the registrar body invokes the handler methods,
    /// and <c>FactoryGenerator.RelayHandler.cs</c> applies no accessibility filter, so
    /// private handler methods compile today. A sibling holder that hosted the registrar
    /// would be CS0122 for those.
    /// </remarks>
    private static void RenderRegistrarHolder(StringBuilder sb, RelayHandlerModel model)
    {
        sb.AppendLine($"    internal static class {RegistrarHolderPrefix}{model.ClassName}");
        sb.AppendLine("    {");
        sb.AppendLine("        internal static void FactoryServiceRegistrar(IServiceCollection services, NeatooFactory remoteLocal)");
        sb.AppendLine("        {");
        sb.AppendLine($"            global::{model.Namespace}.{model.ClassName}.FactoryServiceRegistrar(services, remoteLocal);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// Fully-qualified name of the runtime dispatch-phase enum, as literal text.
    /// </summary>
    /// <remarks>
    /// Text, not a type reference: the enum cannot be referenced from this netstandard2.0
    /// project without duplicating a public runtime type (see the warning on
    /// <c>FactoryEventHandlerAttribute&lt;T&gt;</c>).
    /// <para>
    /// <c>global::</c>-qualified for the same reason as the assembly attribute above, and it
    /// is load-bearing for the same reason: a consumer namespace shadowing the first segment
    /// of this one would otherwise bind the argument to the wrong type. The generated file's
    /// <c>using Neatoo.RemoteFactory;</c> is not enough — that bug shipped for four releases
    /// on the attribute before v1.7.0, and this is a new type-bearing token in the same file.
    /// </para>
    /// </remarks>
    private const string DispatchPhaseType = "global::Neatoo.RemoteFactory.DispatchPhase";

    /// <summary>
    /// Server-side: register into FactoryEventHandlerRegistry at the phase the attribute
    /// declared. Handlers run in the caller's DI scope; <c>Immediate</c> handlers dispatch at
    /// raise time (shared DbContext/transaction), later phases are queued and drained at their
    /// drain point. [Service] parameters resolve from the caller's sp. CancellationToken flows
    /// through from IFactoryEvents.Raise. Invocation arguments are emitted in the order the
    /// user declared them on the handler method.
    /// </summary>
    /// <remarks>
    /// The widest overload — phase AND coalesce — is emitted for every handler, including
    /// unphased/unflagged ones, so there is one shape to read and one path to test: the
    /// defaulted case pins <c>Immediate</c> and <c>false</c> positively rather than pinning
    /// an absence. This leaves the two- and three-argument <c>RegisterHandler</c> overloads
    /// with no generated call sites; they stay because they are public API.
    /// </remarks>
    private static void RenderServerSideHandler(StringBuilder sb, EventHandlerEntry handler, string className)
    {
        var eventTypeName = handler.EventTypeName;

        // An empty name means the consumer cast an undefined value onto the enum; render it
        // faithfully rather than coercing it to a phase they did not ask for.
        // InvariantCulture on the numeric fallback: interpolation would format with the
        // build machine's CurrentCulture, and a negative value on a culture whose negative
        // sign is not ASCII '-' (sv-SE resolves to U+2212 under ICU) emits a CS1056 into the
        // consumer's build. `(DispatchPhase)(-1)` compiles, so the path is reachable.
        var phase = handler.PhaseName.Length > 0
            ? $"{DispatchPhaseType}.{handler.PhaseName}"
            : $"({DispatchPhaseType}){handler.PhaseValue.ToString(CultureInfo.InvariantCulture)}";

        // Emit arguments in declaration order so a handler like
        // `(TestEvent evt, CancellationToken ct, [Service] IFoo svc)` binds correctly.
        var allParamIdentifiers = string.Join(", ",
            handler.AllParameters.Select(p => p.IsCancellationToken ? "ct" : p.Name));

        var serviceAssignments = string.Join("\n                    ",
            handler.ServiceParameters.Select(p => $"var {p.Name} = sp.GetRequiredService<{p.Type}>();"));

        var methodInvocation = $"await {className}.{handler.MethodName}({allParamIdentifiers}).ConfigureAwait(false);";

        sb.AppendLine("            if (NeatooRuntime.IsServerRuntime)");
        sb.AppendLine("            {");
        var coalesce = handler.Coalesce ? "coalesce: true" : "coalesce: false";

        sb.AppendLine($"                FactoryEventHandlerRegistry.RegisterHandler<{eventTypeName}>(typeof({className}), {phase}, {coalesce}, async (sp, eventObj, options, ct) =>");
        sb.AppendLine("                {");
        sb.AppendLine($"                    var {handler.Parameters.First(p => !p.IsCancellationToken).Name} = ({eventTypeName})eventObj;");
        if (!string.IsNullOrEmpty(serviceAssignments))
        {
            sb.AppendLine($"                    {serviceAssignments}");
        }
        sb.AppendLine($"                    {methodInvocation}");
        sb.AppendLine("                });");
        sb.AppendLine("            }");
    }
}
