#nullable enable

using System.Linq;
using System.Text;
using Neatoo.RemoteFactory.Generator.Model;

namespace Neatoo.RemoteFactory.Generator.Renderer;

/// <summary>
/// Renders server-side FactoryEventHandlerRegistry registrations for
/// [FactoryEventHandler&lt;T&gt;] classes with static handler methods. Client-side relay
/// emission and event-type trimming preservation have been removed — event preservation
/// is provided by <c>[DynamicallyAccessedMembers]</c> on <c>FactoryEventBase</c>.
/// </summary>
internal static class RelayHandlerRenderer
{
    public static string Render(RelayHandlerModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        foreach (var u in model.Usings)
        {
            sb.AppendLine(u);
        }

        sb.AppendLine();

        // Assembly-level attribute for trimming-safe factory discovery
        sb.AppendLine($"[assembly: Neatoo.RemoteFactory.NeatooFactoryRegistrar(typeof({model.Namespace}.{model.ClassName}))]");
        sb.AppendLine();

        sb.AppendLine("/*");
        sb.AppendLine("    READONLY - DO NOT EDIT!!!!");
        sb.AppendLine("    Generated by Neatoo.RemoteFactory");
        sb.AppendLine("*/");

        sb.AppendLine($"namespace {model.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    {model.ClassSignatureText} {{");
        sb.AppendLine();

        sb.AppendLine("        internal static void FactoryServiceRegistrar(IServiceCollection services, NeatooFactory remoteLocal)");
        sb.AppendLine("        {");

        foreach (var entry in model.Entries)
        {
            // Every entry is a static handler — the transform silently filters instance methods.
            RenderServerSideHandler(sb, entry, model.ClassName);
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Server-side: register into FactoryEventHandlerRegistry. Handlers run in the
    /// caller's DI scope (shared DbContext/transaction), sequentially, awaited.
    /// [Service] parameters resolve from the caller's sp. CancellationToken flows
    /// through from IFactoryEvents.Raise. Invocation arguments are emitted in the
    /// order the user declared them on the handler method.
    /// </summary>
    private static void RenderServerSideHandler(StringBuilder sb, EventHandlerEntry handler, string className)
    {
        var eventTypeName = handler.EventTypeName;

        // Emit arguments in declaration order so a handler like
        // `(TestEvent evt, CancellationToken ct, [Service] IFoo svc)` binds correctly.
        var allParamIdentifiers = string.Join(", ",
            handler.AllParameters.Select(p => p.IsCancellationToken ? "ct" : p.Name));

        var serviceAssignments = string.Join("\n                    ",
            handler.ServiceParameters.Select(p => $"var {p.Name} = sp.GetRequiredService<{p.Type}>();"));

        var methodInvocation = $"await {className}.{handler.MethodName}({allParamIdentifiers}).ConfigureAwait(false);";

        sb.AppendLine("            if (NeatooRuntime.IsServerRuntime)");
        sb.AppendLine("            {");
        sb.AppendLine($"                FactoryEventHandlerRegistry.RegisterHandler<{eventTypeName}>(typeof({className}), async (sp, eventObj, options, ct) =>");
        sb.AppendLine("                {");
        sb.AppendLine($"                    var {handler.Parameters.First(p => !p.IsCancellationToken).Name} = ({eventTypeName})eventObj;");
        if (!string.IsNullOrEmpty(serviceAssignments))
        {
            sb.AppendLine($"                    {serviceAssignments}");
        }
        sb.AppendLine($"                    {methodInvocation}");
        sb.AppendLine("                });");
        sb.AppendLine("            }");
    }
}
