// src/Generator/Renderer/StaticFactoryRenderer.cs
// Renders factories for static classes with [Execute] methods.

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Neatoo.RemoteFactory.Generator.Model;

namespace Neatoo.RemoteFactory.Generator.Renderer;

/// <summary>
/// Renders factory code for static classes with [Execute] methods.
/// </summary>
internal static class StaticFactoryRenderer
{
    /// <summary>
    /// Renders the complete factory source code for a static class.
    /// </summary>
    public static string Render(FactoryGenerationUnit unit)
    {
        var model = unit.StaticFactory!;

        var sb = new StringBuilder();

        // Header
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Using statements
        foreach (var u in unit.Usings)
        {
            sb.AppendLine(u);
        }

        sb.AppendLine();

        // Assembly-level attribute for trimming-safe factory discovery.
        // Targets the generated registrar holder, NEVER the user's own class: the
        // attribute's [DynamicallyAccessedMembers] preserves every method on whatever
        // type it names, bodies included, so naming the user's class would ship their
        // [Remote] server-only bodies to a trimmed client (TRIM-008).
        sb.AppendLine($"[assembly: Neatoo.RemoteFactory.NeatooFactoryRegistrar(typeof(global::{unit.Namespace}.{RegistrarHolderPrefix}{model.TypeName}))]");
        sb.AppendLine();

        sb.AppendLine("/*");
        sb.AppendLine("    READONLY - DO NOT EDIT!!!!");
        sb.AppendLine("    Generated by Neatoo.RemoteFactory");
        sb.AppendLine("*/");

        sb.AppendLine($"namespace {unit.Namespace}");
        sb.AppendLine("{");

        // Partial class with delegates and service registrar
        sb.AppendLine($"    {model.SignatureText} {{");
        sb.AppendLine();

        // Delegate declarations
        foreach (var del in model.Delegates)
        {
            RenderDelegate(sb, del);
        }

        sb.AppendLine();

        // FactoryServiceRegistrar. Stays on the user's partial class deliberately —
        // its body calls the [Execute] domain methods, which are `private static` by
        // convention (see Design AllPatterns.cs), so a sibling type cannot reach them.
        RenderFactoryServiceRegistrar(sb, model);

        sb.AppendLine("    }");

        // Registrar holder — the assembly attribute's DAM target. Exists so the DAM
        // blast radius is this one forwarding method instead of every method on the
        // user's class. Top-level rather than nested: the proven in-tree shape
        // (EventPreservationRenderer) is top-level, and DAM's behavior toward nested
        // types is not something this repo has verified.
        sb.AppendLine();
        RenderRegistrarHolder(sb, unit, model);
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void RenderDelegate(StringBuilder sb, ExecuteDelegateModel del)
    {
        // Build parameter declarations (exclude CancellationToken, then add optional one at end)
        var paramDecl = string.Join(", ", del.Parameters.Select(p => $"{p.Type} {p.Name}"));
        if (!string.IsNullOrEmpty(paramDecl))
        {
            paramDecl += ", ";
        }
        paramDecl += "CancellationToken cancellationToken = default";

        var nullableMarker = del.IsNullable ? "Nullable" : "";

        sb.AppendLine($"        public delegate Task<{del.ReturnType}> {del.DelegateName}({paramDecl});");
    }

    /// <summary>
    /// Prefix for the generated registrar holder type. Mirrored as a literal in
    /// AssemblyAttributeEmissionTests so a rename fails loudly rather than silently
    /// repointing the attribute.
    /// </summary>
    /// <remarks>
    /// Deliberately a PREFIX, not a suffix. A suffixed name (<c>MyCommandsNeatooFactoryRegistrar</c>)
    /// is a prefix-extension of the user's type, so <c>global::Ns.MyCommands</c> remains a
    /// substring of the holder's fully-qualified name — which makes the "attribute must not
    /// name the consumer's type" regression assertion a false red, and an unclosed
    /// <c>Contains("typeof(global::Ns.MyCommands")</c> a false green. Prefixing breaks the
    /// namespace-qualified substring outright, so the assertion means what it says.
    /// The relay leg uses a distinct prefix so the two never collide on a class carrying
    /// both attributes (see Deferred Work item 15).
    /// </remarks>
    internal const string RegistrarHolderPrefix = "NeatooFactoryRegistrar_";

    /// <summary>
    /// Emits the holder the assembly attribute points at. It does nothing but forward
    /// to the real registrar on the user's partial class — the indirection exists
    /// purely so the attribute's [DynamicallyAccessedMembers] has a single-method type
    /// to preserve instead of the user's whole class.
    /// </summary>
    private static void RenderRegistrarHolder(StringBuilder sb, FactoryGenerationUnit unit, StaticFactoryModel model)
    {
        sb.AppendLine($"    internal static class {RegistrarHolderPrefix}{model.TypeName}");
        sb.AppendLine("    {");
        sb.AppendLine("        internal static void FactoryServiceRegistrar(IServiceCollection services, NeatooFactory remoteLocal)");
        sb.AppendLine("        {");
        sb.AppendLine($"            global::{unit.Namespace}.{model.TypeName}.FactoryServiceRegistrar(services, remoteLocal);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static void RenderFactoryServiceRegistrar(StringBuilder sb, StaticFactoryModel model)
    {
        sb.AppendLine("        internal static void FactoryServiceRegistrar(IServiceCollection services, NeatooFactory remoteLocal)");
        sb.AppendLine("        {");

        // Remote registrations
        sb.AppendLine("            if(remoteLocal == NeatooFactory.Remote)");
        sb.AppendLine("            {");

        foreach (var del in model.Delegates)
        {
            RenderRemoteDelegateRegistration(sb, del, model.TypeName);
        }

        sb.AppendLine("            }");
        sb.AppendLine();

        // Local registrations
        sb.AppendLine("            if(remoteLocal == NeatooFactory.Logical || remoteLocal == NeatooFactory.Server)");
        sb.AppendLine("            {");

        foreach (var del in model.Delegates)
        {
            RenderLocalDelegateRegistration(sb, del, model.TypeName);
        }

        sb.AppendLine("            }");

        // DTO constructor registrations (IL trimming support)
        if (model.DtoReturnTypes.Count > 0 || model.DtoPreserveTypes.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("            // DTO constructor registrations (IL trimming support)");
            foreach (var dtoType in model.DtoReturnTypes)
            {
                sb.AppendLine($"            DtoConstructorRegistry.Register<{dtoType}>(() => new {dtoType}());");
            }

            foreach (var dtoType in model.DtoPreserveTypes)
            {
                sb.AppendLine($"            DtoConstructorRegistry.PreserveType<{dtoType}>();");
            }
        }

        sb.AppendLine("        }");
    }

    private static void RenderRemoteDelegateRegistration(StringBuilder sb, ExecuteDelegateModel del, string typeName)
    {
        // Build parameter declarations (with optional CancellationToken at end)
        var paramDecl = string.Join(", ", del.Parameters.Select(p => $"{p.Type} {p.Name}"));
        if (!string.IsNullOrEmpty(paramDecl))
        {
            paramDecl += ", ";
        }
        paramDecl += "CancellationToken cancellationToken = default";

        // Parameter identifiers (with cancellationToken at end)
        var paramIdentifiers = string.Join(", ", del.Parameters.Select(p => p.Name));
        if (!string.IsNullOrEmpty(paramIdentifiers))
        {
            paramIdentifiers += ", ";
        }
        paramIdentifiers += "cancellationToken";

        // Serialized parameters (exclude CancellationToken)
        var serializedParams = string.Join(", ", del.Parameters.Select(p => p.Name));

        var nullableText = del.IsNullable ? "Nullable" : "";

        sb.AppendLine($"                services.AddTransient<{typeName}.{del.DelegateName}>(cc =>");
        sb.AppendLine("                {");
        sb.AppendLine($"                    return ({paramIdentifiers}) => cc.GetRequiredService<IMakeRemoteDelegateRequest>().ForDelegate{nullableText}<{del.ReturnType}>(typeof({typeName}.{del.DelegateName}), [{serializedParams}], cancellationToken);");
        sb.AppendLine("                });");
    }

    private static void RenderLocalDelegateRegistration(StringBuilder sb, ExecuteDelegateModel del, string typeName)
    {
        // Build parameter declarations (with optional CancellationToken at end)
        var paramDecl = string.Join(", ", del.Parameters.Select(p => $"{p.Type} {p.Name}"));
        if (!string.IsNullOrEmpty(paramDecl))
        {
            paramDecl += ", ";
        }
        paramDecl += "CancellationToken cancellationToken = default";

        // Service assignments
        var serviceAssignments = string.Join("\n                        ",
            del.ServiceParameters.Select(p => $"var {p.Name} = cc.GetRequiredService<{p.Type}>();"));

        // All parameter identifiers for the domain method call (including services and CancellationToken if domain method has it)
        var allParamIdentifiers = BuildDomainMethodInvocationParams(del);

        // Feature switch guard -- when IsServerRuntime=false, the trimmer removes the entire registration
        // The delegate body routes through FactoryEntryCall (PHASE-003): the delegate IS the
        // static pattern's local execution seam — its entry marks the factory call, drains
        // AfterCommit at the outermost successful completion, and discards deferred work on
        // failure. Service resolution sits inside the entry, so a missing server-only service
        // counts as entry failure (clear, no drain). The guard wraps the registration itself,
        // so no async state machine ever hosts it.
        sb.AppendLine("                if (NeatooRuntime.IsServerRuntime)");
        sb.AppendLine("                {");
        sb.AppendLine($"                    services.AddTransient<{typeName}.{del.DelegateName}>(cc =>");
        sb.AppendLine("                    {");
        sb.AppendLine($"                        return ({paramDecl}) => FactoryEntryCall.RunAsync(cc, () => {{");

        if (!string.IsNullOrEmpty(serviceAssignments))
        {
            sb.AppendLine($"                        {serviceAssignments}");
        }

        sb.AppendLine($"                        return {typeName}.{del.Name}({allParamIdentifiers});");
        sb.AppendLine("                        });");
        sb.AppendLine("                    });");
        sb.AppendLine("                }");
    }

    private static string BuildDomainMethodInvocationParams(ExecuteDelegateModel del)
    {
        // Build the full parameter list including services
        var allParams = new List<string>();

        // Add data parameters (already in order)
        allParams.AddRange(del.Parameters.Select(p => p.Name));

        // Add service parameters
        allParams.AddRange(del.ServiceParameters.Select(p => p.Name));

        // Only add cancellationToken if the domain method actually has it
        if (del.HasCancellationToken)
        {
            allParams.Add("cancellationToken");
        }

        return string.Join(", ", allParams);
    }
}
