// src/Generator/Renderer/StaticFactoryRenderer.cs
// Renders factories for static classes with [Execute] methods.

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Neatoo.RemoteFactory.Generator.Model;

namespace Neatoo.RemoteFactory.Generator.Renderer;

/// <summary>
/// Renders factory code for static classes with [Execute] methods.
/// </summary>
internal static class StaticFactoryRenderer
{
    /// <summary>
    /// Renders the complete factory source code for a static class.
    /// </summary>
    public static string Render(FactoryGenerationUnit unit)
    {
        var model = unit.StaticFactory!;

        var sb = new StringBuilder();

        // Header
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Using statements
        foreach (var u in unit.Usings)
        {
            sb.AppendLine(u);
        }

        sb.AppendLine();

        // Assembly-level attribute for trimming-safe factory discovery
        sb.AppendLine($"[assembly: Neatoo.RemoteFactory.NeatooFactoryRegistrar(typeof(global::{unit.Namespace}.{model.TypeName}))]");
        sb.AppendLine();

        sb.AppendLine("/*");
        sb.AppendLine("    READONLY - DO NOT EDIT!!!!");
        sb.AppendLine("    Generated by Neatoo.RemoteFactory");
        sb.AppendLine("*/");

        sb.AppendLine($"namespace {unit.Namespace}");
        sb.AppendLine("{");

        // Partial class with delegates and service registrar
        sb.AppendLine($"    {model.SignatureText} {{");
        sb.AppendLine();

        // Delegate declarations
        foreach (var del in model.Delegates)
        {
            RenderDelegate(sb, del);
        }

        sb.AppendLine();

        // FactoryServiceRegistrar
        RenderFactoryServiceRegistrar(sb, model);

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void RenderDelegate(StringBuilder sb, ExecuteDelegateModel del)
    {
        // Build parameter declarations (exclude CancellationToken, then add optional one at end)
        var paramDecl = string.Join(", ", del.Parameters.Select(p => $"{p.Type} {p.Name}"));
        if (!string.IsNullOrEmpty(paramDecl))
        {
            paramDecl += ", ";
        }
        paramDecl += "CancellationToken cancellationToken = default";

        var nullableMarker = del.IsNullable ? "Nullable" : "";

        sb.AppendLine($"        public delegate Task<{del.ReturnType}> {del.DelegateName}({paramDecl});");
    }

    private static void RenderFactoryServiceRegistrar(StringBuilder sb, StaticFactoryModel model)
    {
        sb.AppendLine("        internal static void FactoryServiceRegistrar(IServiceCollection services, NeatooFactory remoteLocal)");
        sb.AppendLine("        {");

        // Remote registrations
        sb.AppendLine("            if(remoteLocal == NeatooFactory.Remote)");
        sb.AppendLine("            {");

        foreach (var del in model.Delegates)
        {
            RenderRemoteDelegateRegistration(sb, del, model.TypeName);
        }

        sb.AppendLine("            }");
        sb.AppendLine();

        // Local registrations
        sb.AppendLine("            if(remoteLocal == NeatooFactory.Logical || remoteLocal == NeatooFactory.Server)");
        sb.AppendLine("            {");

        foreach (var del in model.Delegates)
        {
            RenderLocalDelegateRegistration(sb, del, model.TypeName);
        }

        sb.AppendLine("            }");

        // DTO constructor registrations (IL trimming support)
        if (model.DtoReturnTypes.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("            // DTO constructor registrations (IL trimming support)");
            foreach (var dtoType in model.DtoReturnTypes)
            {
                sb.AppendLine($"            DtoConstructorRegistry.Register<{dtoType}>(() => new {dtoType}());");
            }
        }

        sb.AppendLine("        }");
    }

    private static void RenderRemoteDelegateRegistration(StringBuilder sb, ExecuteDelegateModel del, string typeName)
    {
        // Build parameter declarations (with optional CancellationToken at end)
        var paramDecl = string.Join(", ", del.Parameters.Select(p => $"{p.Type} {p.Name}"));
        if (!string.IsNullOrEmpty(paramDecl))
        {
            paramDecl += ", ";
        }
        paramDecl += "CancellationToken cancellationToken = default";

        // Parameter identifiers (with cancellationToken at end)
        var paramIdentifiers = string.Join(", ", del.Parameters.Select(p => p.Name));
        if (!string.IsNullOrEmpty(paramIdentifiers))
        {
            paramIdentifiers += ", ";
        }
        paramIdentifiers += "cancellationToken";

        // Serialized parameters (exclude CancellationToken)
        var serializedParams = string.Join(", ", del.Parameters.Select(p => p.Name));

        var nullableText = del.IsNullable ? "Nullable" : "";

        sb.AppendLine($"                services.AddTransient<{typeName}.{del.DelegateName}>(cc =>");
        sb.AppendLine("                {");
        sb.AppendLine($"                    return ({paramIdentifiers}) => cc.GetRequiredService<IMakeRemoteDelegateRequest>().ForDelegate{nullableText}<{del.ReturnType}>(typeof({typeName}.{del.DelegateName}), [{serializedParams}], cancellationToken);");
        sb.AppendLine("                });");
    }

    private static void RenderLocalDelegateRegistration(StringBuilder sb, ExecuteDelegateModel del, string typeName)
    {
        // Build parameter declarations (with optional CancellationToken at end)
        var paramDecl = string.Join(", ", del.Parameters.Select(p => $"{p.Type} {p.Name}"));
        if (!string.IsNullOrEmpty(paramDecl))
        {
            paramDecl += ", ";
        }
        paramDecl += "CancellationToken cancellationToken = default";

        // Service assignments
        var serviceAssignments = string.Join("\n                        ",
            del.ServiceParameters.Select(p => $"var {p.Name} = cc.GetRequiredService<{p.Type}>();"));

        // All parameter identifiers for the domain method call (including services and CancellationToken if domain method has it)
        var allParamIdentifiers = BuildDomainMethodInvocationParams(del);

        // Feature switch guard -- when IsServerRuntime=false, the trimmer removes the entire registration
        sb.AppendLine("                if (NeatooRuntime.IsServerRuntime)");
        sb.AppendLine("                {");
        sb.AppendLine($"                    services.AddTransient<{typeName}.{del.DelegateName}>(cc =>");
        sb.AppendLine("                    {");
        sb.AppendLine($"                        return ({paramDecl}) => {{");

        if (!string.IsNullOrEmpty(serviceAssignments))
        {
            sb.AppendLine($"                        {serviceAssignments}");
        }

        sb.AppendLine($"                        return {typeName}.{del.Name}({allParamIdentifiers});");
        sb.AppendLine("                        };");
        sb.AppendLine("                    });");
        sb.AppendLine("                }");
    }

    private static string BuildDomainMethodInvocationParams(ExecuteDelegateModel del)
    {
        // Build the full parameter list including services
        var allParams = new List<string>();

        // Add data parameters (already in order)
        allParams.AddRange(del.Parameters.Select(p => p.Name));

        // Add service parameters
        allParams.AddRange(del.ServiceParameters.Select(p => p.Name));

        // Only add cancellationToken if the domain method actually has it
        if (del.HasCancellationToken)
        {
            allParams.Add("cancellationToken");
        }

        return string.Join(", ", allParams);
    }
}
